#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 7

#### getdeb
#wget http://archive.getdeb.net/install_deb/getdeb-repository_0.1-1~getdeb1_all.deb
#sudo dpkg -i getdeb-repository_0.1-1~getdeb1_all.deb
#rm -f getdeb-repository_0.1-1~getdeb1_all.deb

#### playdeb
#wget http://archive.getdeb.net/install_deb/playdeb_0.3-1~getdeb1_all.deb
#sudo dpkg -i playdeb_0.3-1~getdeb1_all.deb
#rm -f playdeb_0.3-1~getdeb1_all.deb

#### krita testing
#sudo apt-fast -y install krita-testing krita-testing-dbg krita-testing-l10n		#testing
#sudo restart lightdm
#to execute run "krita"
#sudo apt-fast -y install krita kde-l10n-es calligra-l10n-es	# official
#sudo add-apt-repository ppa:kubuntu-ppa/backports		# another method
#sudo apt-fast update
#sudo apt-fast install krita kritasketch

#### pepper-flash - for chromium (2)
#https://launchpad.net/~skunk/+archive/ubuntu/pepper-flash
#sudo add-apt-repository -y ppa:skunk/pepper-flash
#sudo apt-fast -y update
#sudo apt-fast -y install pepflashplugin-nonfree
#/etc/chromium-browser/default
#. /usr/lib/pepflashplugin-installer/pepflashplayer.sh
#chromium restart

#### nuvolaplayer 2 - ONLY 14.10
#sudo add-apt-repository -y ppa:nuvola-player-builders/stable
#sudo apt-fast -y update
#sudo apt-fast -y upgrade
#sudo apt-fast -y install nuvolaplayer

#### gnoduino	14.04
#sudo add-apt-repository -y ppa:pmjdebruijn/gnoduino-release
#sudo apt-fast -y update
#sudo apt-fast -y install gnoduino

##### Telegram (1b)
#Exec=bash -c "unset QT_STYLE_OVERRIDE ; /home/usuario/Telegram/Telegram -- %u"

#test -f /usr/share/applications/telegram.desktop || sudo sh -c 'echo "[Desktop Entry]
#Type=Application
#Name=Telegram
#Comment=Official desktop version of Telegram messaging app
#Categories=Network
#Exec=/home/usuario/Telegram/Telegram -- %u
#Icon=/home/usuario/Telegram/td_logo.png" >> /usr/share/applications/telegram.desktop'

##### Telegram (2) - NOT UPDATABLE IN-APP FROM PPA, ONLY IF A NEWER ON PPA IS PUBLISHED
##/opt/telegram/Telegram -- %u
#sudo add-apt-repository -y ppa:atareao/telegram
#sudo apt-fast -y update
#sudo apt-fast -y install telegram

##### Telegram (3) - NOT UPDATABLE IN-APP FROM PPA, ONLY IF A NEWER ON PPA IS PUBLISHED
#sudo add-apt-repository -y ppa:noobslab/apps
#sudo apt-fast -y update
#sudo apt-fast -y install telegram-desktop

##### Frostwire - go to web or getdeb - ancient version
#wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
#test -f /etc/apt/sources.list.d/getdeb_apps.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
#test -f /etc/apt/sources.list.d/getdeb_games.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'
#sudo apt-fast -y update
#sudo apt-fast -y install frostwire

#### unattended-upgrades - NOT WORKING
#http://almamu.com/wordpress/configurar-las-actualizaciones-automaticas-en-ubuntu-server/
#http://241931348f64b1d1.wordpress.com/2013/01/24/how-to-configure-automatic-update-on-ubuntu-server/
#http://www.redeszone.net/2014/12/12/habilita-las-actualizaciones-de-seguridad-automaticas-en-ubuntu/
#http://www.taringa.net/posts/linux/13681417/Instalar-automaticamente-actualizaciones-en-Ubuntu.html
#http://askubuntu.com/questions/172524/how-can-i-check-if-automatic-updates-are-enabled#172527
sudo apt-fast -y install unattended-upgrades
sudo dpkg-reconfigure -plow unattended-upgrades

## /etc/apt/apt.conf.d/10periodic

#Replace this:

#APT::Periodic::Update-Package-Lists "1";
#APT::Periodic::Download-Upgradeable-Packages "0";
#APT::Periodic::AutocleanInterval "0";

#With this:

#APT::Periodic::Enable "1";
#APT::Periodic::Update-Package-Lists "1";
#APT::Periodic::Download-Upgradeable-Packages "1";
#APT::Periodic::AutocleanInterval "5";
#APT::Periodic::Unattended-Upgrade "1";
#APT::Periodic::RandomSleep "1800";

## /etc/apt/apt.conf.d/50unattended-upgrades
#uncomment - "${distro_id}:${distro_codename}-updates";

#### canonical-kernel-team - Possibly Unstable - Not recommendable
#sudo add-apt-repository -y ppa:canonical-kernel-team/ppa
#sudo apt-fast -y update
#sudo apt-fast -y dist-upgrade

#### VirtualBox (2)
#wget -q -O - http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc | sudo apt-key add -
#test -f /etc/apt/sources.list.d/virtualbox.org.list || sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian utopic non-free contrib" >> /etc/apt/sources.list.d/virtualbox.org.list'
#sudo apt-fast -y update
#sudo apt-fast -y upgrade
#sudo apt-fast -y install virtualbox-4.3 virtualbox-guest-additions-iso virtualbox-guest-utils virtualbox-guest-x11 virtualbox-qt

#### syncthing - OUTDATED
#sudo add-apt-repository -y ppa:ytvwld/syncthing
#sudo apt-fast -y update
#sudo apt-fast -y install syncthing

#### Ubuplus - PRECISE
#sudo add-apt-repository -y ppa:luismtc20/ppa
#sudo apt-fast -y update
#sudo apt-fast -y install ubuplus

#### jupiter	#POSSIBLY DEPRECATED
#sudo add-apt-repository -y ppa:webupd8team/jupiter
#sudo apt-fast -y update
#sudo apt-fast -y install jupiter


