#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 4

######## Backup & Sync

#### holo-backup
apps4/holo-backup

#### insync
apps4/insync

#### spideroak
apps4/spideroak

#### Various
sudo apt-fast -y install sbackup-plugins-fuse grsync unison-gtk		#http://planetubuntu.es/post/como-sincronizar-2-equipos-de-manera-bidireccional-con-unison

########OS & Utilities

#### intel-linux-graphics-installer - Official - Not compatible with 16.04 - Now 15.10
apps4/intel-linux-graphics-installer

#### mucommander-unstable
apps4/mucommander-unstable

#### gnome3-team
apps4/gnome3-team

#### apt-new
apps4/apt-new

#### x-updates - only recommended for latest graphic cards drivers - less updated than ppa:xorg-edgers/ppa
apps4/x-updates

#### winusb
apps4/winusb

#### psensor
apps4/psensor 

#### voice-commands
apps4/voice-commands

#### Various
sudo apt-fast -y install inxi	# http://lamiradadelreplicante.com/2014/10/27/toda-la-informacion-de-tu-sistema-linux-con-inxi/
sudo apt-fast -y install laptop-mode-tools	#gksu lmt-config-gui - This to launch it
sudo apt-fast -y install libfile-mimeinfo-perl catfish
sudo apt-fast -y install qtnx usb-imagewriter gddrescue testdisk baobab gsmartcontrol calendar-indicator
sudo apt-fast -y install gnome-system-tools gnome-tweak-tool
#sudo apt-fast -y install checkbox-qt - SYSTEM TESTING APP
sudo apt-fast -y install indicator-netspeed launchy
sudo apt-fast -y install xscreensaver-gl xscreensaver-gl-extra
sudo apt-fast -y install alarm-clock gmrun lm-sensors tmux xbindkeys xbindkeys-config htop pcmanfm

########Desktop Environment

#### unity8
apps4/unity8

#### gnome-session-fallback
sudo apt-fast -y install gnome-session-fallback

#### lxqt
apps4/lxqt

#### budgie-desktop
apps4/budgie-desktop

#### razorqt
apps4/razorqt

#### cinnamon
apps4/cinnamon

#### mate-desktop-environment
apps4/mate-desktop-environment

#### enlightenment
apps4/enlightenment

########Themes

#### noobslab-themes
apps4/noobslab-themes

#### paper-gtk-theme
apps4/paper-gtk-theme

#### ambiance-radiance-themes
apps4/ambiance-radiance-themes

######## Security & Privacy
sudo apt-fast -y install seahorse

######## CD/DVD Tools

#### Various
sudo apt-fast -y install furiusisomount devede isomaster k3b acetoneiso 

######## Photos & Graphics

#### gthumb
apps4/gthumb

#### photo
apps4/photo 

#### Various
sudo apt-fast -y install shotwell
sudo apt-fast -y install xnviewmp xsane
sudo apt-fast -y install karbon scribus gwenview		#scribus-ng - DEV VERSION

######## Audio & Music

#### spotify - ONLY FOR 64 BITS - TO USE 32 GO TO http://repository.spotify.com/pool/non-free/s/spotify/
apps4/spotify

#### blockify
apps4/blockify

#### pykaraoke
apps4/pykaraoke

#### Various
sudo apt-fast -y install sound-juicer mixxx qtractor ardour3 performous

######## Videos & Movies

#### obs-studio
apps4/obs-studio

#### recordmydesktop
sudo apt-fast -y install recordmydesktop gtk-recordmydesktop

#### kazam-unstable
apps4/kazam-unstable

#### simplescreenrecorder
apps4/simplescreenrecorder

#### popcorn-time
apps4/popcorn-time

#### waifu
apps4/waifu

####All multimedia content

##best performance on flash
#http://blog.timvalenta.com/2013/01/chromes-fullscreen-flash-performance-is-slow-laggy-and-heartwrenching/
sudo apt-fast -y install non-free-codecs libxine1-ffmpeg gxine mencoder libmpcdec6 libquicktime2 flac faac faad sox ffmpeg2theora libmpeg2-4 uudeview libmpeg3-1 mpeg3-utils mpegdemux liba52-0.7.4-dev mpeg2dec vorbis-tools id3v2 mpg321 mpg123 libflac++6 ffmpeg libmp4v2-2 icedax tagtool easytag id3tool lame libmad0 libjpeg-progs
sudo apt-fast -y install libavcodec-extra libdvdread4 libappindicator1 x264 uudeview
sudo /usr/share/doc/libdvdread4/./install-css.sh
sudo apt-fast -y install gstreamer0.10-ffmpeg gstreamer0.10-fluendo-mp3 gstreamer0.10-gnonlin gstreamer0.10-plugins-bad-multiverse totem gstreamer-dbus-media-service gstreamer-tools
sudo apt-fast -y install gsfonts gsfonts-x11 ttf-liberation ttf-droid ttf-dejavu libdvdcss2 w64codecs

######## Development

##### enigma - http://enigma-dev.org/docs/Wiki/Install:Linux
#more...

##### makehuman
apps4/makehuman

#### ubuntu-make - (new android studio) http://www.webupd8.org/2014/12/ubuntu-developer-tools-center-renamed.html
apps4/ubuntu-make

#### wine
apps4/wine

#### wine-staging
apps4/wine-staging

#### vineyard-testing (recommended vine extra)
apps4/vineyard-testing

#### atom
apps4/atom

#### sublime-text
apps4/sublime-text

#### oracle-java
apps4/oracle-java

#### Various
#sudo apt-fast -y install ia32-libs lib32asound2		#REMOVED 
sudo apt-fast -y install libcurl3 libc6-i386 lib32z1

sudo apt-fast -y install terminator zenity gtk3-engines-unico octave-zenity
sudo apt-fast -y install vim

#sudo apt-fast -y install ubuntu-developer-tools-center udtc android		#DEPRECATED
sudo apt-fast -y install geany geany-plugin-spellcheck geany-plugin-addons geany-plugin-extrasel
#sudo apt-fast -y install qt4-demos

#sudo apt-fast -y install notepad-qml qtcreator #### Dependencies problem, be careful.
sudo apt-fast -y install mono-complete mono-basic-dbg

######## Web Browsers

#### chromium-dev
apps4/chromium-dev

#### chromium-beta
apps4/chromium-beta

#### firefox-dev (aurora - fx10)
apps4/firefox-dev

#### firefox-daily
apps4/firefox-daily

#### midori
apps4/midori

#### iridium-browser
apps4/iridium-browser

#### liri-browser
apps4/liri-browser

#### superbird-browser - not working, needs a library
apps4/superbird-browser

#### srware-iron-browser - to add more steps
apps4/srware-iron-browser

######## Social

#### hotot - May be in official repo
apps4/hotot

#### pidgin-developers
apps4/pidgin-developers

#### telegram-purple
apps4/telegram-purple

#### Various
sudo apt-fast -y install choqok xchat

######## File Management

#### thunar
sudo apt-fast -y install thunar thunar-data thunar-volman libthunarx-2-0 thunar-archive-plugin thunar-media-tags-plugin ffmpegthumbnailer
sudo apt-fast -y install xfce4-goodies

#### Various
sudo apt-fast -y install lhasa filezilla mc

######## File Sharing

##### qbittorrent
apps4/qbittorrent

##### vuze
apps4/vuze

#### Various
sudo apt-fast -y install amule deluge axel

######## News & Books

#### quiterss
apps4/quiterss

#### Various
sudo apt-fast -y install gpodder calibre newsbeuter rssowl

######## Office & Productivity

#### Office web apps
#cd ..
#sudo dpkg -i ./z.extra/microsoft_online_apps.deb

#### Various
sudo apt-fast -y install okular evince lyx rednotebook zim txt2tags poppler-utils pdftk
sudo apt-fast -y install gnucash (python-gnucash) grisbi hombank skrooge abtransfers codeka adempiere (sugarcrm - not in repos)

######## Games

#### 0ad
apps4/0ad

#### lutris
apps4/lutris

#### dustrac
apps4/dustrac

#### Various
#sudo apt-fast -y install true-combat-elite
#americas-army:i386
#lincity-ng
#crossover-games crossover-pro
#gamedevelop
#ogs-mahjong ogs-mahjong-music-addon
#sandboxgamemaker
#opencity
#teeworlds
#d2x-rebirth-full d2x-xl-executable
#numptyphysics
#kolf
#neverputt
#maximinigolf
#assaultcube
#sorr
#iconqueru
#hedgewars
#freeminer
#torcs
#vdrift
#trigger-rally
#stuntrally
#speed-dreams
#gweled
#sgt-puzzles
#kulic
#amor macopix-gtk2 oneko

######## Extra

####Upgrading system
#sudo apt-fast -y upgrade

#### Wine example
#wget http://dl.desktop.line.naver.jp/naver/LINE/win/LineInst.exe
#wine LineInst.exe

#### Repairing jdownloader v1 if is necessary
#sudo update-alternatives --config java

#### Various
#sudo apt-fast -y install diodon diodon-plugins
