#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 5

#### lshw
sudo apt-fast -y install lshw-gtk

#### conky-manager
apps5/conky-manager

#### clicompanion
apps5/clicompanion

#### photoqt
apps5/photoqt

#### power-installer
apps5/power-installer

#### kdeconnect
apps5/kdeconnect

#### touchpad-indicator
apps5/touchpad-indicator

#### qllauncher
apps5/qllauncher

#### hollywood
apps5/hollywood

#### trojita
apps5/trojita

#### bum
sudo apt-fast -y install bum

#### thewindowfactory (twf)
sudo apt-fast -y install thewindowfactory

######## ONLY FOR UBUNTU WITH UNITY SURELY

#### tint2 - http://www.howtogeek.com/189819/how-to-add-a-taskbar-to-the-desktop-in-ubuntu-14.04/
sudo apt-fast -y install tint2
#at start:
#Taskbar - Tint2
#tint2
#Windows-like Taskbar

#### classicmenu-indicator_unsettings
apps5/classicmenu-indicator_unsettings

#### unity-tweak-tool
apps5/unity-tweak-tool

#### window-list_indicator-places - http://www.noobslab.com/2014/08/useful-panel-indicators-collection-for.html
apps5/window-list_indicator-places

#### indicator-systemtray-unity
apps5/indicator-systemtray-unity

#### ubuntu-tweak
apps5/ubuntu-tweak

#### gnome-tweak-tool
sudo apt-fast -y install gnome-tweak-tool

#### cpu-frequency-scaling
apps5/cpu-frequency-scaling

#### my-weather-indicator
apps5/my-weather-indicator

######## ONLY FOR KUBUNTU

#### Various
sudo apt-fast -y install muon