#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 3

######## Backup & Sync

#### backintime-stable
apps3/backintime-stable

#### DirSyncPro
apps3/dirsyncpro

#### systemback
apps3/systemback

#### syncany
apps3/syncany

#### sparkleshare
apps3/sparkleshare

#### aptik - http://www.howtogeek.com/206454/how-to-backup-and-restore-your-apps-and-ppas-in-ubuntu-using-aptik/
apps3/aptik

#### timeShift
apps3/timeshift

#### syncthing-gtk
apps3/syncthing-gtk

######## OS & Utilities

#### alltray
sudo apt-fast -y install alltray

#### gnome-pie
apps3/gnome-pie

#### KeeWeb
apps3/KeeWeb

#### gnome-schedule
#sudo apt-fast -y install gnome-schedule
#sudo crontab -e
#sudo gnome-schedule
#update
#sudo apt-fast -y update && sudo apt-fast -y upgrade

#### partitionmanager (kde)
sudo apt-fast -y install partitionmanager

#### qterminal
apps3/qterminal

#### regexxer
sudo apt-fast -y install regexxer

#### searchmonkey
sudo apt-fast -y install searchmonkey

#### haguichi
apps3/haguichi

#### guake
apps3/guake

#### tlp
apps3/tlp

#### zenmap
sudo apt-fast -y install zenmap

#### burg - https://advancedpcusers.wordpress.com/2012/07/01/replace-grub-with-burg-graphical-boot-loader/
apps3/burg

#### customizer (u-customizer)
apps3/customizer

#### gnome-multiwriter
apps3/gnome-multiwrite

#### ubuntu-touch-coreapps
apps3/ubuntu-touch-coreapps

#### pushbullet-indicator
apps3/pushbullet-indicator

#### albert
apps3/albert

#### mutate
apps3/mutate

#### undistract-me - http://lamiradadelreplicante.com/2015/01/15/undistract-me-nos-avisa-cuando-un-comando-ha-terminado-de-ejecutarse-en-la-terminal/
sudo apt-fast -y install undistract-me

#### variety-peterlevi-daily
apps3/variety-peterlevi-daily

#### HP
sudo apt-fast -y install hplip hplip-gui

#### phoronix-test-suite
apps3/phoronix-test-suite

#### bibletime
apps3/bibletime

#### ubuntu customization kit
sudo apt-fast -y install uck

#### xenial-mate on 16.04 - on 16.10 not necessary
#apps3/xenial-mate

######## Desktop Environment

#

######## Themes

#### folder-color
apps3/folder-color

######## Language packages

#

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#

######## Audio & Music

#### flowblade
#sudo apt-fast -y install flowblade
#Read https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md
#wget ...
#sudo dpkg -i ./flowblade-1.8.0-1_all.deb

#### lightworks
apps3/gradio

#### lightworks
apps3/lightworks

#### tomahawk
apps3/tomahawk

#### nuvolaplayer3-devel
apps3/nuvolaplayer3-devel

#### pogo
apps3/pogo

######## Videos & Movies

#### kodi-nightly
apps3/kodi-nightly

#### kodi-stable
#apps3/kodi-stable

#### lmms
apps3/lmms

#### muse
sudo apt-fast -y install muse

#### audacity
apps3/audacity

#### ocenaudio
apps3/ocenaudio

#### hydrogen
sudo apt-fast -y install hydrogen

#### natron
apps3/natron

#### cinelerra
apps3/cinelerra

#### kdenlive - CAREFULL, a lot of kde packages
apps3/kdenlive

#### openshot
sudo apt-fast -y install openshot

#### pitivi
sudo apt-fast -y install pitivi

#### shotcut
apps3/shotcut

######## All multimedia content

#

######## Development

#### ubuntu-emulator
#http://www.webupd8.org/2014/03/ubuntu-touch-emulator-installation-and.html
#http://www.webupd8.org/2013/11/experimental-ubuntu-touch-emulator.html
sudo apt-fast -y install ubuntu-emulator

#### freecad
apps3/freecad

######## Web Browsers

#### qutebrowser
apps3/qutebrowser

#### i2p
apps3/i2p

######## Social

##### qtox
apps3/qtox

##### utox
apps3/utox

######## File Management

#

######## File Sharing

##### frostwire
apps3/frostwire

##### tribler
apps3/tribler

#### xdman
apps3/xdman

######## News & Books

#

######## Office & Productivity

##### lothumbnailer
apps3/lothumbnailer

##### gscan2pdf
apps3/gscan2pdf

#### geary
apps3/geary

#### pantheon-mail
apps3/pantheon-mail

#### evolution-staging
apps3/evolution-staging

#### claws-mail
apps3/claws-mail

######## Games

#### openra - install getdeb before
sudo apt-fast -y install openra

#### zandronum
apps3/zandronum

#### Various
sudo apt-fast -y install violetland bofh
#sudo apt-fast -y install scourge csmash cdogs-sdl djl
