#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 6

#### sigram - MATE PROBLEM
sudo add-apt-repository -y ppa:sialan/desktop
sudo apt-fast -y update
sudo apt-fast -y install sigram

#### cutegram - MATE PROBLEM
sudo add-apt-repository -y ppa:aseman/desktop-apps
sudo apt-fast -y update
sudo apt-fast -y install cutegram libqtelegram

#### indicator-usb - tested and fail!
sudo add-apt-repository -y ppa:yunnxx/gnome3
sudo apt-fast -y update
sudo apt-fast -y install indicator-usb

#### SpaceFM - problems
sudo add-apt-repository -y ppa:mati75/lubuntu
sudo apt-fast -y update
sudo apt-fast -y install spacefm

#### Ubuntu phone sdk - With problems
#sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
#sudo add-apt-repository -y ppa:alexey-ivanov/qtcreator - BE CAREFUL
#sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper - DEPRECATED, NEVER USE
#sudo add-apt-repository -y ppa:ui-toolkit/ppa - DEPRECATED, NEVER USE
#sudo apt-fast -y update
#sudo apt-fast -y install ubuntu-sdk qml
#qtmultimedia5-examples
#sudo apt-fast -y install qtcreator qt5-default - DON'T USE

#### syncdrive - dependencies error
sudo add-apt-repository -y ppa:nemh/gambas3
sudo add-apt-repository -y ppa:noobslab/pear-apps
sudo apt-fast -y update
sudo apt-fast -y install syncdrive

#### grive-tools
sudo add-apt-repository -y ppa:thefanclub/grive-tools
sudo apt-fast -y update
sudo apt-fast -y install grive-tools

#### ualinux
#http://www.ualinux.com/en/how-to-connect # Be careful, it installs a special search google provider
wget http://archive.ualinux.com/ubuntu/main/all/ualinux-repository.deb
sudo dpkg -i ualinux*.deb
rm ualinux*.deb
sudo apt-fast -y update
sudo apt-fast -y dist-upgrade

#### compiz + cairo-dock + emerald
sudo apt-fast -y install compizconfig-settings-manager compiz fusion-icon compiz-plugins
sudo apt-fast -y install cairo-dock cairo-dock-plug-ins-data cairo-dock-plug-ins cairo-dock-data cairo-dock-core cairo-dock-plug-ins-integration cairo-dock-plug-ins-dbus-interface-python libgldi3

#### emerald
sudo add-apt-repository -y ppa:brainpower/testing
sudo apt-fast -y update
sudo apt-fast -y install emerald

#### remastersys - PRECISE but works on RARING - systemback is preferible
wget -O - http://www.remastersys.com/ubuntu/remastersys.gpg.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/remastersys.list || sudo sh -c 'echo "deb http://www.remastersys.com/ubuntu precise main" >> /etc/apt/sources.list.d/remastersys.list'
sudo apt-fast -y update
sudo apt-fast -y install remastersys remastersys-gui ubiquity-frontend-gtk ubiquity-slideshow-lubuntu bootchart 

#### multisystem
wget -q http://liveusb.info/multisystem/depot/multisystem.asc -O- | sudo apt-key add -
test -f /etc/apt/sources.list.d/multisystem.list || sudo sh -c 'echo "deb http://liveusb.info/multisystem/depot all main" >> /etc/apt/sources.list.d/multisystem.list'
sudo apt-fast -y update
sudo apt-fast -y install multisystem

#### ultraStar-deluxe - http://ultrastardx.sourceforge.net/usdx-downloads/usdx/ - dependencies error
#https://launchpad.net/~jon-severinsson/+archive/ubuntu/ffmpeg
#https://launchpad.net/~tobydox/+archive/ubuntu/ultrastardx

######## TO INSTALL MANUALLY

#### http://labs.sialan.org/projects/limoo

#### http://www.opera.com/download/guide/?os=linux

#### http://www.time4popcorn.eu/

######## ERROR - PROBLEMS
#sudo apt-fast -y install quickly quickly-widgets
#sudo apt-fast -y install python-snippets acire libvte-2.90-dev libvte-dev python-vte desktopcouch  #### ERROR
#sudo apt-fast -y install cairo-compmgr cairo-compmgr-plugins  #### POSSIBLY DEPENDENCIES ERROR
#sudo apt-fast -y install mountmanager ntfsprogs  #### ERROR
#sudo apt-fast -y install wally wallch

#### uninstallpackages
#### ONLY FOR UBUNTU
#sudo apt-fast remove -y webbrowser-app unity-lens* unity-scope*

######## Possibly needless programs
#sudo apt-fast -y remove openjdk-6-jre openjdk-6-jdk icedtea-6-plugin

######## ONLY FOR LUBUNTU
#sudo apt-fast remove -y chromium-browser firefox
#sudo apt-fast remove -y abiword-common abiword libabiword-2.9 sylpheed sylpheed-plugins sylpheed-doc sylpheed-i18n gnumeric-common gnumeric xpad mtpaint evince-common evince ace-of-penguins
#sudo apt-fast remove -y gxine libxine1 libxine1-x mplayer2
#sudo apt-fast remove -y libgmtk0 libgmtk0-data libgmlib0

######## installpackagesproblematic

#### audacious, unity-reboot, etc
#sudo add-apt-repository -y ppa:nilarimogard/webupd8
#sudo apt-fast -y update
#sudo apt-fast -y install unity-reboot audacious

#### dockbarx
#sudo add-apt-repository -y ppa:dockbar-main/ppa
#sudo apt-fast -y update
#sudo apt-fast -y install dockbarx
 
#### docky-development PPA & stable
#sudo add-apt-repository -y ppa:docky-core/ppa
#sudo add-apt-repository -y ppa:docky-core/stable
#sudo apt-fast -y update
#sudo apt-fast -y install docky

#### gnome-do
#sudo add-apt-repository -y ppa:do-testers/ppa
#sudo apt-fast -y update
#sudo apt-fast -y install gnome-do

#### avant-window-navigator
#sudo add-apt-repository -y ppa:awn-testing/ppa - not for 14.04
#sudo apt-fast -y update
#sudo apt-fast -y install avant-window-navigator

######## Not free codecs
#sudo apt-fast -y install nautilus-script-audio-convert flashplugin-nonfree-extrasound:i386 icedtea-plugin w32codecs

#### Various
#sudo apt-fast -y install acroread-common acroread acroread-fonts
#sudo apt-fast -y install aptoncd
#sudo apt-fast -y install gadmin-rsync mate-core
#sudo apt-fast -y install mounty ddrescue  #### NEED TO ADD PPA
#sudo apt-fast -y install eog eog-plugins
#sudo apt-fast -y install metacity