#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 1

#### Remove all your repos
#sudo rm -f -r /etc/apt/sources.list.d/*

#### Upgrading system
#sudo apt-fast -y update
#sudo apt-fast -y upgrade
##sudo apt-fast -y dist-upgrade
##sudo apt-fast -y install xxx --no-remove --force-yes

######## Backup & Sync

#### 1.freefilesync - official repositories
#apps1/1.freefilesync

#### 2.dropbox - deb
#apps1/2.dropbox

#### 3.megasync - deb
#apps1/3.megasync

######## OS & Utilities

#### 4.apt-fast - ppa
apps1/4.apt-fast

#### 5.y-ppa-manager - ppa
##(aunchpad-getkeys + missing gpg-keys + gpg badsig errors
apps1/5.y-ppa-manager

#### 6.getdeb - deb
apps1/6.getdeb

#### 7.playdeb - deb
apps1/7.playdeb

#### 8.mtp-support - official repositories
apps1/8.mtp-support

#### 9.xorg-edgers - ppa
##Possibly Unstable - Contains "bleeding-edge" graphics/system packages which may be unstable - more updated than ppa:ubuntu-x-swat/x-updates
#apps1/9.xorg-edgers

#### 10.oibaf - ppa
##Possibly Unstable
#apps1/10.oibaf

#### 11.graphics-drivers-team - ppa
##Possibly Unstable
#apps1/11.graphics-drivers-team

#### 12.keepassx - official repositories
#ppa:keepassx/daily - not updated
apps1/12.keepassx

#### 13.ubuntu-restricted-extras - official repositories
apps1/13.ubuntu-restricted-extras

#### 14.ttf-ancient-fonts - official repositories
apps1/14.ttf-ancient-fonts

#### 15.synaptic - official repositories
apps1/15.synaptic

#### 16.preload - official repositories
apps1/16.preload

#### 17.prelink - official repositories
apps1/17.prelink

#### 18.gdebi - official repositories
apps1/18.gdebi

#### 19.ppa-purge - official repositories
apps1/19.ppa-purge

#### 20.gnome-disk-utility - official repositories
apps1/20.gnome-disk-utility

#### 21.gparted - official repositories
apps1/21.gparted

#### 22.gkrellm - official repositories
#apps1/22.gkrellm

#### 23.mate-tweak - official repositories
#apps1/23.mate-tweak

#### 24.recoll - official repositories
apps1/24.recoll

#### 25.brasero - official repositories
apps1/25.brasero

#### 26.k3b - official repositories
#apps1/26.k3b

#### 27.gtkorphan - official repositories
apps1/27.gtkorphan

#### 28.byobu - official repositories
## for remove old kernels:
#byobu
#sudo purge-old-kernels
apps1/28.byobu

#### 29.gsmartcontrol - official repositories
apps1/29.gsmartcontrol

#### 30.software-center - official repositories
apps1/30.software-center

#### 31.gnome-software - official repositories
apps1/31.gnome-software

#### 32.test
#apps1/32.test

#### 33.appgrid - ppa
##error
#apps1/33.appgrid

#### 34.mintStick - deb
apps1/34.mintStick

#### 130.spaceview - ppa
#apps1/130.spaceview

#### 132.ukku - deb
#apps1/132.ukku

#### 35.mate-dock-applet - ppa
apps1/35.mate-dock-applet

#### 36.extundelete - official repositories
##http://rootear.com/ubuntu-linux/recuperar-archivos-borrados-extundelete
apps1/36.extundelete

#### 37.cairo-dock - ppa
#apps1/37.cairo-dock

#### 38.ubuntu-after-install - ppa
##error
#apps1/38.ubuntu-after-install

#### 39.ubutricks - sh
#apps1/39.ubutricks

#### 40.postinstallerf - deb
#apps1/40.postinstallerf

#### 41.teamviewer - deb
apps1/41.teamviewer

#### 42.converseen - ppa
apps1/42.converseen

#### 43.synapse - ppa
apps1/43.synapse

#### 44.grub-customizer - ppa
apps1/44.grub-customizer

#### 45.bleachbit - official repositories
apps1/45.bleachbit

#### 46.clipit - ppa
#apps1/46.clipit

#### 47.screenfetch - official repositories
apps1/47.screenfetch

#### 48.i-nex - ppa
##http://i-nex.linux.pl/install/ - https://launchpad.net/i-nex/+download
apps1/48.i-nex

#### 49.ANGRYsearch - tar.gz
#apps1/49.ANGRYsearch

#### 50.fish-shell - ppa
#apps1/50.fish-shell

#### 51.furiusisomount - official repositories
#apps1/51.furiusisomount

#### 52.ddrescue-gui - ppa
#apps1/52.ddrescue-gui

#### 53.unetbootin - ppa
#apps1/53.unetbootin

#### 54.manpages-es - official repositories
#http://ubunlog.com/poner-las-guias-man-espanol-ubuntu/?utm_source=feedburner&utm_medium=%24%7Bfeed%2C+email%7D&utm_campaign=Feed%3A+%24%7BUbunlog%7D+%28%24%7BUbunlog%7D%29
apps1/54.manpages-es

#### 55.asterisk-on-cli-passwords - config
apps1/55.asterisk-on-cli-passwords

#### 56.disable-system-crash-reports - config
#apps1/56.disable-system-crash-reports

######## Desktop Environment

#

######## Themes

#### 57.vibrancy-colors icon theme - ppa
apps1/57.vibrancy-colors

#### 58.flatabulous theme - ppa
## not working
#apps1/58.flatabulous-theme

######## Language packages - official repositories

#### 59.aspell - official repositories
apps1/59.aspell

#### 60.myspell - official repositories
#apps1/60.myspell

######## Security & Privacy

#### 61.gufw - official repositories
apps1/61.gufw

######## CD/DVD Tools

#

######## Photos & Graphics

#### 62.gimp - ppa
#apps1/62.gimp

#### 63.gimp-edge - ppa
apps1/63.gimp-edge

#### 64.krita-testing - ppa
##apps1/krita/krita.appimage
apps1/64.krita-testing

#### 65.gnome-exe-thumbnailer - official repositories
apps1/65.gnome-exe-thumbnailer

#### 66.shutter - official repositories
apps1/66.shutter

#### 67.inkscape-stable - ppa
#apps1/67.inkscape-stable

#### 68.inkscape-trunk - ppa
#apps1/68.inkscape-trunk

######## Audio & Music

#### 69.qmmp - ppa
apps1/69.qmmp

######## Videos & Movies

#### 70.kazam - official repositories
apps1/70.kazam

#### 71.sopcast - tar.gz
#apps1/71.sopcast

#### 72.smplayer + mpv support - ppa
#apps1/72.smplayer

#### 73.handbrake - official repositories
#apps1/73.handbrake

######## All multimedia content

#### 74.ffmpeg - official repositories
apps1/74.ffmpeg

#### 75.vlc-stable - ppa
#sudo apt-fast -y install vlc
apps/75.vlc-stable

#### 76.vlc-daily - ppa
#apps1/76.vlc-daily

######## Development

#### 77.notepadqq - ppa
apps1/77.notepadqq

#### 78.openjdk-8 - official repositories
apps1/78.openjdk-8

#### 79. openjdk-7 - official repositories
#apps1/79.openjdk-7

#### 80.meld - official repositories
apps1/80.meld

#### 81.dev-utils - official repositories
#apps1/81.dev-utils

#### 82.git-stable - ppa
#apps1/82.git-stable

#### 83.smartgit - deb
#apps1/83.smartgit

#### 84.flatpak - ppa
#apps1/84.flatpak

#### 85.dia - ppa
#apps1/85.dia

#### 86.blender - ppa
#apps1/86.blender

#### 87.fritzing - ppa
#apps1/87.fritzing

#### 88.uecide - ppa
#apps1/88.uecide

#### 89.arduino-ide - tar.xz
#apps1/89.arduino-ide

#### 90.arduino-studio - deb
#apps1/90.arduino-studio

#### 91.git-rc - ppa
#apps1/91.git-rc

#### 92.git-gui - official repositories
#apps1/92.git-gui

#### 93.Qt-Linux - run
#apps1/93.Qt-Linux

#### 94.kicad - ppa
#apps1/94.kicad

######## Web Browsers

#### 100.vivaldi-browser - deb
## in script pepperflash is added
#apps1/100.vivaldi-browser

#### 101.google-chrome-stable - ppa
#apps1/101.google-chrome-stable

#### 102.google-chrome-unstable - ppa
apps1/102.google-chrome-unstable

#### 103.chromium stable - official repositories
#apps1/103.chromium

#### 104.firefox - official repositories
#apps1/104.firefox

#### 105.firefox-trunk - ppa
apps1/105.firefox-trunk

#### 106.ubuntu-mozilla-security - ppa
#apps1/106.ubuntu-mozilla-security

#### 107.pepper-flash-for-chromium - official repositories
## Not working
##apps1/107.pepper-flash-for-chromium

#### 108.pepper-flash-for-firefox - official repositories - ppa
## Not working
##apps1/108.pepper-flash-for-firefox

#### 109.tor-browser - ppa
#apps1/109.tor-browser

######## Social

#### 110.skype - deb
#apps1/110.skype

##### 111.mumble - ppa
#apps1/111.mumble

##### 112.wire - deb
#apps1/112.wire

##### 113.telegram - tar.xz
## http://deshack.net/install-telegram-for-linux-as-an-application/
#apps1/113.telegram

##### 114.Facebook-Messenger-Desktop - deb
#apps1/114.Facebook-Messenger-Desktop

##### 115.Whatsie - ppa
#apps1/115.Whatsie

######## File Management

#### 116.compress-uncompress-utils - official repositories
apps1/116.compress-uncompress-utils

######## File Sharing

#### 117.jdownloader-beta - ppa
apps1/117.jdownloader-beta

#### 118.jdownloader-stable - ppa
#apps1/118.jdownloader-stable

#### 119.peerflix - ppa
#apps1/119.peerflix

#### 120.samba - official repositories
#apps1/120.samba

######## News & Books

#

######## Office & Productivity

#### 121.evolution - official repositories
apps1/121.evolution

#### 122.libreoffice - ppa
apps1/122.libreoffice

#### 123.qpdfview - official repositories
#apps1/123.qpdfview

##### 124.Thunderbird-nightly - tar.bz2
#apps1/124.thunderbird-nightly

######## Games

##### 125.steam - deb
#apps1/125.steam

######## Extra

#### 126.uninstallpackages
apps1/126.uninstallpackages

#### Repairing system 2/2
sudo apt-fast -f -y install
#sudo dpkg --configure -a
#sudo apt-fast -y --fix-broken install

#### Upgrading system
#sudo apt-fast -y upgrade
#sudo apt-fast -y dist-upgrade
#sudo do-release-update

#### Cleaning system
sudo apt-fast -y autoremove
#sudo apt-fast -y autoclean
#sudo apt-fast -y clean
