#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 2

######## Backup & Sync

#

######## OS & Utilities

#

######## Desktop Environment

#

######## Themes

#

######## Language packages

#

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#

######## Audio & Music

#

######## Videos & Movies

#

######## Development

#

######## Web Browsers

#

######## File Management

#

######## File Sharing

#

######## News & Books

#

######## Office & Productivity

#

######## Games

#
