Document: ubunsys
Title: Debian ubunsys Manual
Author: <insert document author here>
Abstract: This manual describes what ubunsys is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ubunsys/ubunsys.sgml.gz

Format: postscript
Files: /usr/share/doc/ubunsys/ubunsys.ps.gz

Format: text
Files: /usr/share/doc/ubunsys/ubunsys.text.gz

Format: HTML
Index: /usr/share/doc/ubunsys/html/index.html
Files: /usr/share/doc/ubunsys/html/*.html
