#!/bin/bash

#### acestream (14.04)
#http://askubuntu.com/questions/763364/how-to-watch-acestream-sopcast-ubuntu-16-04-lts
sudo wget -O - http://repo.acestream.org/keys/acestream.public.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/acestream.list || sudo sh -c 'echo "deb http://repo.acestream.org/ubuntu/ trusty main" >> /etc/apt/sources.list.d/acestream.list'
sudo apt-fast -y update
#sudo apt-fast -y install acestream-full
sudo apt-fast -y install acestream-engine

#to use acestream, execute:
#acestreamengine --client-console