#!/bin/bash

#### owncloud
wget -q -O - http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_15.10/Release.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/owncloud-client.list || sudo sh -c 'echo "deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10/ /" >> /etc/apt/sources.list.d/owncloud-client.list'
sudo apt-fast -y update
sudo apt-fast -y install owncloud-client

#wget http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_15.10/Release.key
#sudo apt-key add - < Release.key
#sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10/ /' >> /etc/apt/sources.list.d/owncloud-client.list"