#!/bin/bash

#### aptik - http://www.howtogeek.com/206454/how-to-backup-and-restore-your-apps-and-ppas-in-ubuntu-using-aptik/
sudo apt-add-repository -y ppa:teejee2008/ppa
sudo apt-fast -y update
sudo apt-fast -y install aptik