#!/bin/bash

#### haguichi
sudo add-apt-repository -y ppa:webupd8team/haguichi
sudo apt-fast -y update
sudo apt-fast -y install haguichi

wget https://secure.logmein.com/labs/logmein-hamachi_2.1.0.139-1_amd64.deb
sudo dpkg -i logmein-hamachi_2.1.0.139-1_amd64.deb