#!/bin/bash

#### lmms
wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_9.1.0~kxstudio1_all.deb
sudo dpkg -i kxstudio-repos_9.1.0~kxstudio1_all.deb
sudo apt-fast -y install lmms

#### lmms (to test)
#sudo add-apt-repository -y ppa:kxstudio-debian/apps
#sudo add-apt-repository -y ppa:kxstudio-debian/libs
#sudo add-apt-repository -y ppa:kxstudio-debian/music
#sudo add-apt-repository -y ppa:kxstudio-debian/plugins
#sudo apt-fast -y update
#sudo apt-fast -y install lmms
