#!/bin/bash

#### megatools
wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.2_1.0.2e-1_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/m/megatools/megatools_1.9.96-1_amd64.deb
sudo dpkg -i libssl1.0.2_1.0.2e-1_amd64.deb
sudo dpkg -i megatools_1.9.96-1_amd64.deb
rm libssl1.0.2_1.0.2e-1_amd64.deb
rm megatools_1.9.96-1_amd64.deb