/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionExit;
    QAction *actionPaste;
    QAction *actionAbout;
    QAction *actionAbout_Qt;
    QAction *actionSave_as;
    QAction *actionNew;
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionCopy;
    QAction *actionCut;
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab_4;
    QPushButton *unselectAllButton;
    QPushButton *selectAllButton;
    QPushButton *installSelectedPackagesButton;
    QPushButton *uninstallSelectedPackagesButton;
    QPushButton *loadSelectionButton;
    QPushButton *saveSelectionButton;
    QTabWidget *tabWidget_2;
    QWidget *tab_11;
    QCheckBox *checkBox_012;
    QCheckBox *checkBox_013;
    QCheckBox *checkBox_014;
    QCheckBox *checkBox_009;
    QCheckBox *checkBox_011;
    QCheckBox *checkBox_020;
    QCheckBox *checkBox_010;
    QCheckBox *checkBox_021;
    QCheckBox *checkBox_008;
    QCheckBox *checkBox_015;
    QCheckBox *checkBox_005;
    QCheckBox *checkBox_016;
    QCheckBox *checkBox_017;
    QCheckBox *checkBox_018;
    QCheckBox *checkBox_004;
    QCheckBox *checkBox_006;
    QCheckBox *checkBox_022;
    QCheckBox *checkBox_007;
    QCheckBox *checkBox_023;
    QCheckBox *checkBox_024;
    QCheckBox *checkBox_025;
    QCheckBox *checkBox_026;
    QCheckBox *checkBox_027;
    QCheckBox *checkBox_028;
    QCheckBox *checkBox_029;
    QCheckBox *checkBox_030;
    QCheckBox *checkBox_031;
    QCheckBox *checkBox_032;
    QCheckBox *checkBox_033;
    QCheckBox *checkBox_034;
    QCheckBox *checkBox_035;
    QCheckBox *checkBox_036;
    QCheckBox *checkBox_037;
    QCheckBox *checkBox_046;
    QCheckBox *checkBox_045;
    QCheckBox *checkBox_044;
    QCheckBox *checkBox_043;
    QCheckBox *checkBox_042;
    QCheckBox *checkBox_047;
    QCheckBox *checkBox_048;
    QCheckBox *checkBox_049;
    QCheckBox *checkBox_050;
    QCheckBox *checkBox_051;
    QCheckBox *checkBox_052;
    QCheckBox *checkBox_053;
    QCheckBox *checkBox_054;
    QCheckBox *checkBox_055;
    QCheckBox *checkBox_056;
    QCheckBox *checkBox_041;
    QCheckBox *checkBox_038;
    QCheckBox *checkBox_040;
    QCheckBox *checkBox_039;
    QCheckBox *checkBox_003;
    QCheckBox *checkBox_001;
    QCheckBox *checkBox_002;
    QCheckBox *checkBox_019;
    QCheckBox *checkBox_057;
    QWidget *tab_12;
    QCheckBox *checkBox_058;
    QCheckBox *checkBox_060;
    QCheckBox *checkBox_059;
    QCheckBox *checkBox_061;
    QCheckBox *checkBox_065;
    QCheckBox *checkBox_064;
    QCheckBox *checkBox_063;
    QCheckBox *checkBox_066;
    QCheckBox *checkBox_067;
    QCheckBox *checkBox_062;
    QCheckBox *checkBox_068;
    QCheckBox *checkBox_069;
    QCheckBox *checkBox_072;
    QCheckBox *checkBox_070;
    QCheckBox *checkBox_073;
    QCheckBox *checkBox_071;
    QCheckBox *checkBox_075;
    QCheckBox *checkBox_076;
    QCheckBox *checkBox_074;
    QCheckBox *checkBox_093;
    QCheckBox *checkBox_078;
    QCheckBox *checkBox_081;
    QCheckBox *checkBox_085;
    QCheckBox *checkBox_094;
    QCheckBox *checkBox_083;
    QCheckBox *checkBox_082;
    QCheckBox *checkBox_080;
    QCheckBox *checkBox_084;
    QCheckBox *checkBox_092;
    QCheckBox *checkBox_091;
    QCheckBox *checkBox_088;
    QCheckBox *checkBox_087;
    QCheckBox *checkBox_090;
    QCheckBox *checkBox_089;
    QCheckBox *checkBox_079;
    QCheckBox *checkBox_086;
    QCheckBox *checkBox_077;
    QCheckBox *checkBox_101;
    QCheckBox *checkBox_105;
    QCheckBox *checkBox_107;
    QCheckBox *checkBox_110;
    QCheckBox *checkBox_108;
    QCheckBox *checkBox_100;
    QCheckBox *checkBox_113;
    QCheckBox *checkBox_112;
    QCheckBox *checkBox_104;
    QCheckBox *checkBox_109;
    QCheckBox *checkBox_111;
    QCheckBox *checkBox_102;
    QCheckBox *checkBox_115;
    QCheckBox *checkBox_114;
    QCheckBox *checkBox_103;
    QCheckBox *checkBox_106;
    QCheckBox *checkBox_117;
    QCheckBox *checkBox_118;
    QCheckBox *checkBox_116;
    QWidget *tab_5;
    QCheckBox *checkBox_132;
    QCheckBox *checkBox_130;
    QCheckBox *checkBox_120;
    QCheckBox *checkBox_123;
    QCheckBox *checkBox_122;
    QCheckBox *checkBox_121;
    QCheckBox *checkBox_126;
    QCheckBox *checkBox_125;
    QCheckBox *checkBox_124;
    QCheckBox *checkBox_119;
    QCheckBox *checkBox_133;
    QCheckBox *checkBox_134;
    QCheckBox *checkBox_135;
    QCheckBox *checkBox_136;
    QCheckBox *checkBox_137;
    QCheckBox *checkBox_138;
    QCheckBox *checkBox_139;
    QCheckBox *checkBox_140;
    QCheckBox *checkBox_141;
    QCheckBox *checkBox_142;
    QCheckBox *checkBox_143;
    QCheckBox *checkBox_144;
    QCheckBox *checkBox_145;
    QCheckBox *checkBox_146;
    QCheckBox *checkBox_147;
    QCheckBox *checkBox_148;
    QCheckBox *checkBox_149;
    QCheckBox *checkBox_131;
    QCheckBox *checkBox_127;
    QCheckBox *checkBox_128;
    QCheckBox *checkBox_129;
    QCheckBox *checkBox_150;
    QWidget *tab_3;
    QTabWidget *tabWidget_3;
    QWidget *tab_6;
    QLabel *label_66;
    QPushButton *doInvisibleAsterisksButton;
    QLabel *label_67;
    QLabel *label_6;
    QLabel *label_63;
    QLabel *label_8;
    QLabel *label_7;
    QPushButton *openSourcesListDButton;
    QLabel *label_64;
    QPushButton *disableHibernationButton;
    QPushButton *doVisibleAsterisksButton;
    QLabel *label_65;
    QPushButton *enableHibernationButton;
    QLabel *label_68;
    QPushButton *enableSudoWithoutPassButton;
    QPushButton *disableSudoWithoutPassButton;
    QLabel *label_10;
    QPushButton *openSudoersFileButton;
    QPushButton *backupSudoersFileButton;
    QWidget *tab_7;
    QPushButton *installTemplatesButton;
    QLabel *label_62;
    QLabel *label_5;
    QWidget *tab;
    QToolBox *toolBox;
    QWidget *page_3;
    QLabel *label_61;
    QPushButton *upgradeLatestDevButton;
    QWidget *page;
    QPushButton *dist_upgradeButton;
    QLabel *label_17;
    QPushButton *cleanKernelsButton;
    QLabel *label_59;
    QLabel *label_60;
    QPushButton *upgradeLatestStableButton;
    QWidget *page_2;
    QPushButton *cleanButton;
    QPushButton *updateAndUpgradeButton;
    QPushButton *basicPackagesInstallButton;
    QPushButton *updateReposButton;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_31;
    QPushButton *upgradeReposButton;
    QLabel *label_25;
    QWidget *tab_2;
    QPushButton *integrityCheckButton;
    QLabel *label_2;
    QLabel *label_3;
    QPushButton *fixBrokenPackagesButton_1;
    QPushButton *fixBrokenPackagesButton_2;
    QPushButton *fixBrokenPackagesButton_3;
    QPushButton *fixBrokenPackagesButton_4;
    QPushButton *fixBrokenPackagesButton_5;
    QPushButton *fixBrokenPackagesButton_6;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_9;
    QPushButton *repairNetworkButton;
    QLabel *label_27;
    QPushButton *repairGPGKeys;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QMenuBar *menuBar;
    QMenu *menuNuevo;
    QMenu *menuEdici_n;
    QMenu *menuAyuda;
    QToolBar *fileToolBar;
    QStatusBar *statusBar;
    QToolBar *editToolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(711, 549);
        QIcon icon;
        icon.addFile(QStringLiteral(":/images/linux-icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionPaste = new QAction(MainWindow);
        actionPaste->setObjectName(QStringLiteral("actionPaste"));
        actionPaste->setEnabled(false);
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/images/paste.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPaste->setIcon(icon1);
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        actionAbout_Qt = new QAction(MainWindow);
        actionAbout_Qt->setObjectName(QStringLiteral("actionAbout_Qt"));
        actionSave_as = new QAction(MainWindow);
        actionSave_as->setObjectName(QStringLiteral("actionSave_as"));
        actionSave_as->setEnabled(false);
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/images/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_as->setIcon(icon2);
        actionNew = new QAction(MainWindow);
        actionNew->setObjectName(QStringLiteral("actionNew"));
        actionNew->setEnabled(false);
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/images/new.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNew->setIcon(icon3);
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        actionOpen->setEnabled(false);
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/images/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen->setIcon(icon4);
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        actionSave->setEnabled(false);
        actionSave->setIcon(icon2);
        actionCopy = new QAction(MainWindow);
        actionCopy->setObjectName(QStringLiteral("actionCopy"));
        actionCopy->setEnabled(false);
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/images/copy.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCopy->setIcon(icon5);
        actionCut = new QAction(MainWindow);
        actionCut->setObjectName(QStringLiteral("actionCut"));
        actionCut->setEnabled(false);
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/images/cut.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCut->setIcon(icon6);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setEnabled(true);
        tabWidget->setGeometry(QRect(9, 10, 691, 451));
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        unselectAllButton = new QPushButton(tab_4);
        unselectAllButton->setObjectName(QStringLiteral("unselectAllButton"));
        unselectAllButton->setGeometry(QRect(600, 30, 81, 23));
        selectAllButton = new QPushButton(tab_4);
        selectAllButton->setObjectName(QStringLiteral("selectAllButton"));
        selectAllButton->setGeometry(QRect(600, 60, 81, 23));
        installSelectedPackagesButton = new QPushButton(tab_4);
        installSelectedPackagesButton->setObjectName(QStringLiteral("installSelectedPackagesButton"));
        installSelectedPackagesButton->setGeometry(QRect(600, 120, 81, 23));
        uninstallSelectedPackagesButton = new QPushButton(tab_4);
        uninstallSelectedPackagesButton->setObjectName(QStringLiteral("uninstallSelectedPackagesButton"));
        uninstallSelectedPackagesButton->setEnabled(false);
        uninstallSelectedPackagesButton->setGeometry(QRect(600, 150, 81, 23));
        uninstallSelectedPackagesButton->setCheckable(false);
        loadSelectionButton = new QPushButton(tab_4);
        loadSelectionButton->setObjectName(QStringLiteral("loadSelectionButton"));
        loadSelectionButton->setGeometry(QRect(600, 210, 81, 23));
        saveSelectionButton = new QPushButton(tab_4);
        saveSelectionButton->setObjectName(QStringLiteral("saveSelectionButton"));
        saveSelectionButton->setEnabled(false);
        saveSelectionButton->setGeometry(QRect(600, 240, 81, 23));
        tabWidget_2 = new QTabWidget(tab_4);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(0, 0, 591, 411));
        tab_11 = new QWidget();
        tab_11->setObjectName(QStringLiteral("tab_11"));
        checkBox_012 = new QCheckBox(tab_11);
        checkBox_012->setObjectName(QStringLiteral("checkBox_012"));
        checkBox_012->setGeometry(QRect(10, 220, 101, 23));
        checkBox_013 = new QCheckBox(tab_11);
        checkBox_013->setObjectName(QStringLiteral("checkBox_013"));
        checkBox_013->setGeometry(QRect(10, 240, 201, 23));
        checkBox_014 = new QCheckBox(tab_11);
        checkBox_014->setObjectName(QStringLiteral("checkBox_014"));
        checkBox_014->setGeometry(QRect(10, 260, 191, 23));
        checkBox_009 = new QCheckBox(tab_11);
        checkBox_009->setObjectName(QStringLiteral("checkBox_009"));
        checkBox_009->setGeometry(QRect(10, 160, 141, 23));
        checkBox_011 = new QCheckBox(tab_11);
        checkBox_011->setObjectName(QStringLiteral("checkBox_011"));
        checkBox_011->setGeometry(QRect(10, 200, 181, 23));
        checkBox_020 = new QCheckBox(tab_11);
        checkBox_020->setObjectName(QStringLiteral("checkBox_020"));
        checkBox_020->setGeometry(QRect(210, 0, 191, 23));
        checkBox_010 = new QCheckBox(tab_11);
        checkBox_010->setObjectName(QStringLiteral("checkBox_010"));
        checkBox_010->setGeometry(QRect(10, 180, 141, 23));
        checkBox_021 = new QCheckBox(tab_11);
        checkBox_021->setObjectName(QStringLiteral("checkBox_021"));
        checkBox_021->setGeometry(QRect(210, 20, 191, 23));
        checkBox_008 = new QCheckBox(tab_11);
        checkBox_008->setObjectName(QStringLiteral("checkBox_008"));
        checkBox_008->setGeometry(QRect(10, 140, 141, 23));
        checkBox_015 = new QCheckBox(tab_11);
        checkBox_015->setObjectName(QStringLiteral("checkBox_015"));
        checkBox_015->setGeometry(QRect(10, 280, 191, 23));
        checkBox_005 = new QCheckBox(tab_11);
        checkBox_005->setObjectName(QStringLiteral("checkBox_005"));
        checkBox_005->setGeometry(QRect(10, 80, 141, 23));
        checkBox_016 = new QCheckBox(tab_11);
        checkBox_016->setObjectName(QStringLiteral("checkBox_016"));
        checkBox_016->setGeometry(QRect(10, 300, 191, 23));
        checkBox_017 = new QCheckBox(tab_11);
        checkBox_017->setObjectName(QStringLiteral("checkBox_017"));
        checkBox_017->setGeometry(QRect(10, 320, 191, 23));
        checkBox_018 = new QCheckBox(tab_11);
        checkBox_018->setObjectName(QStringLiteral("checkBox_018"));
        checkBox_018->setGeometry(QRect(10, 340, 191, 23));
        checkBox_004 = new QCheckBox(tab_11);
        checkBox_004->setObjectName(QStringLiteral("checkBox_004"));
        checkBox_004->setGeometry(QRect(10, 60, 141, 23));
        checkBox_006 = new QCheckBox(tab_11);
        checkBox_006->setObjectName(QStringLiteral("checkBox_006"));
        checkBox_006->setGeometry(QRect(10, 100, 141, 23));
        checkBox_022 = new QCheckBox(tab_11);
        checkBox_022->setObjectName(QStringLiteral("checkBox_022"));
        checkBox_022->setGeometry(QRect(210, 40, 111, 23));
        checkBox_007 = new QCheckBox(tab_11);
        checkBox_007->setObjectName(QStringLiteral("checkBox_007"));
        checkBox_007->setGeometry(QRect(10, 120, 141, 23));
        checkBox_023 = new QCheckBox(tab_11);
        checkBox_023->setObjectName(QStringLiteral("checkBox_023"));
        checkBox_023->setGeometry(QRect(210, 60, 111, 23));
        checkBox_024 = new QCheckBox(tab_11);
        checkBox_024->setObjectName(QStringLiteral("checkBox_024"));
        checkBox_024->setGeometry(QRect(210, 80, 111, 23));
        checkBox_025 = new QCheckBox(tab_11);
        checkBox_025->setObjectName(QStringLiteral("checkBox_025"));
        checkBox_025->setGeometry(QRect(210, 100, 111, 23));
        checkBox_026 = new QCheckBox(tab_11);
        checkBox_026->setObjectName(QStringLiteral("checkBox_026"));
        checkBox_026->setGeometry(QRect(210, 120, 111, 23));
        checkBox_027 = new QCheckBox(tab_11);
        checkBox_027->setObjectName(QStringLiteral("checkBox_027"));
        checkBox_027->setGeometry(QRect(210, 140, 111, 23));
        checkBox_028 = new QCheckBox(tab_11);
        checkBox_028->setObjectName(QStringLiteral("checkBox_028"));
        checkBox_028->setGeometry(QRect(210, 160, 111, 23));
        checkBox_029 = new QCheckBox(tab_11);
        checkBox_029->setObjectName(QStringLiteral("checkBox_029"));
        checkBox_029->setGeometry(QRect(210, 180, 131, 23));
        checkBox_030 = new QCheckBox(tab_11);
        checkBox_030->setObjectName(QStringLiteral("checkBox_030"));
        checkBox_030->setGeometry(QRect(210, 200, 141, 23));
        checkBox_031 = new QCheckBox(tab_11);
        checkBox_031->setObjectName(QStringLiteral("checkBox_031"));
        checkBox_031->setGeometry(QRect(210, 220, 141, 23));
        checkBox_032 = new QCheckBox(tab_11);
        checkBox_032->setObjectName(QStringLiteral("checkBox_032"));
        checkBox_032->setGeometry(QRect(210, 240, 111, 23));
        checkBox_033 = new QCheckBox(tab_11);
        checkBox_033->setObjectName(QStringLiteral("checkBox_033"));
        checkBox_033->setGeometry(QRect(210, 260, 111, 23));
        checkBox_034 = new QCheckBox(tab_11);
        checkBox_034->setObjectName(QStringLiteral("checkBox_034"));
        checkBox_034->setGeometry(QRect(210, 280, 111, 23));
        checkBox_035 = new QCheckBox(tab_11);
        checkBox_035->setObjectName(QStringLiteral("checkBox_035"));
        checkBox_035->setGeometry(QRect(210, 300, 151, 23));
        checkBox_036 = new QCheckBox(tab_11);
        checkBox_036->setObjectName(QStringLiteral("checkBox_036"));
        checkBox_036->setGeometry(QRect(210, 320, 111, 23));
        checkBox_037 = new QCheckBox(tab_11);
        checkBox_037->setObjectName(QStringLiteral("checkBox_037"));
        checkBox_037->setGeometry(QRect(210, 340, 111, 23));
        checkBox_046 = new QCheckBox(tab_11);
        checkBox_046->setObjectName(QStringLiteral("checkBox_046"));
        checkBox_046->setGeometry(QRect(390, 140, 111, 23));
        checkBox_045 = new QCheckBox(tab_11);
        checkBox_045->setObjectName(QStringLiteral("checkBox_045"));
        checkBox_045->setGeometry(QRect(390, 120, 111, 23));
        checkBox_044 = new QCheckBox(tab_11);
        checkBox_044->setObjectName(QStringLiteral("checkBox_044"));
        checkBox_044->setGeometry(QRect(390, 100, 151, 23));
        checkBox_043 = new QCheckBox(tab_11);
        checkBox_043->setObjectName(QStringLiteral("checkBox_043"));
        checkBox_043->setGeometry(QRect(390, 80, 111, 23));
        checkBox_042 = new QCheckBox(tab_11);
        checkBox_042->setObjectName(QStringLiteral("checkBox_042"));
        checkBox_042->setGeometry(QRect(390, 60, 121, 23));
        checkBox_047 = new QCheckBox(tab_11);
        checkBox_047->setObjectName(QStringLiteral("checkBox_047"));
        checkBox_047->setGeometry(QRect(390, 160, 131, 23));
        checkBox_048 = new QCheckBox(tab_11);
        checkBox_048->setObjectName(QStringLiteral("checkBox_048"));
        checkBox_048->setGeometry(QRect(390, 180, 111, 23));
        checkBox_049 = new QCheckBox(tab_11);
        checkBox_049->setObjectName(QStringLiteral("checkBox_049"));
        checkBox_049->setGeometry(QRect(390, 200, 141, 23));
        checkBox_050 = new QCheckBox(tab_11);
        checkBox_050->setObjectName(QStringLiteral("checkBox_050"));
        checkBox_050->setGeometry(QRect(390, 220, 111, 23));
        checkBox_051 = new QCheckBox(tab_11);
        checkBox_051->setObjectName(QStringLiteral("checkBox_051"));
        checkBox_051->setGeometry(QRect(390, 240, 151, 23));
        checkBox_052 = new QCheckBox(tab_11);
        checkBox_052->setObjectName(QStringLiteral("checkBox_052"));
        checkBox_052->setGeometry(QRect(390, 260, 141, 23));
        checkBox_053 = new QCheckBox(tab_11);
        checkBox_053->setObjectName(QStringLiteral("checkBox_053"));
        checkBox_053->setGeometry(QRect(390, 280, 111, 23));
        checkBox_054 = new QCheckBox(tab_11);
        checkBox_054->setObjectName(QStringLiteral("checkBox_054"));
        checkBox_054->setGeometry(QRect(390, 300, 131, 23));
        checkBox_055 = new QCheckBox(tab_11);
        checkBox_055->setObjectName(QStringLiteral("checkBox_055"));
        checkBox_055->setGeometry(QRect(390, 320, 201, 23));
        checkBox_056 = new QCheckBox(tab_11);
        checkBox_056->setObjectName(QStringLiteral("checkBox_056"));
        checkBox_056->setGeometry(QRect(390, 340, 211, 23));
        checkBox_041 = new QCheckBox(tab_11);
        checkBox_041->setObjectName(QStringLiteral("checkBox_041"));
        checkBox_041->setGeometry(QRect(390, 40, 121, 23));
        checkBox_038 = new QCheckBox(tab_11);
        checkBox_038->setObjectName(QStringLiteral("checkBox_038"));
        checkBox_038->setGeometry(QRect(210, 360, 161, 23));
        checkBox_040 = new QCheckBox(tab_11);
        checkBox_040->setObjectName(QStringLiteral("checkBox_040"));
        checkBox_040->setGeometry(QRect(390, 20, 121, 23));
        checkBox_039 = new QCheckBox(tab_11);
        checkBox_039->setObjectName(QStringLiteral("checkBox_039"));
        checkBox_039->setGeometry(QRect(390, 0, 111, 23));
        checkBox_003 = new QCheckBox(tab_11);
        checkBox_003->setObjectName(QStringLiteral("checkBox_003"));
        checkBox_003->setGeometry(QRect(10, 40, 141, 23));
        checkBox_001 = new QCheckBox(tab_11);
        checkBox_001->setObjectName(QStringLiteral("checkBox_001"));
        checkBox_001->setGeometry(QRect(10, 0, 141, 23));
        checkBox_002 = new QCheckBox(tab_11);
        checkBox_002->setObjectName(QStringLiteral("checkBox_002"));
        checkBox_002->setGeometry(QRect(10, 20, 141, 23));
        checkBox_019 = new QCheckBox(tab_11);
        checkBox_019->setObjectName(QStringLiteral("checkBox_019"));
        checkBox_019->setGeometry(QRect(10, 360, 191, 23));
        checkBox_057 = new QCheckBox(tab_11);
        checkBox_057->setObjectName(QStringLiteral("checkBox_057"));
        checkBox_057->setGeometry(QRect(390, 360, 191, 23));
        tabWidget_2->addTab(tab_11, QString());
        tab_12 = new QWidget();
        tab_12->setObjectName(QStringLiteral("tab_12"));
        checkBox_058 = new QCheckBox(tab_12);
        checkBox_058->setObjectName(QStringLiteral("checkBox_058"));
        checkBox_058->setGeometry(QRect(10, 0, 191, 23));
        checkBox_060 = new QCheckBox(tab_12);
        checkBox_060->setObjectName(QStringLiteral("checkBox_060"));
        checkBox_060->setGeometry(QRect(10, 40, 191, 23));
        checkBox_059 = new QCheckBox(tab_12);
        checkBox_059->setObjectName(QStringLiteral("checkBox_059"));
        checkBox_059->setGeometry(QRect(10, 20, 191, 23));
        checkBox_061 = new QCheckBox(tab_12);
        checkBox_061->setObjectName(QStringLiteral("checkBox_061"));
        checkBox_061->setGeometry(QRect(10, 60, 191, 23));
        checkBox_065 = new QCheckBox(tab_12);
        checkBox_065->setObjectName(QStringLiteral("checkBox_065"));
        checkBox_065->setGeometry(QRect(10, 140, 191, 23));
        checkBox_064 = new QCheckBox(tab_12);
        checkBox_064->setObjectName(QStringLiteral("checkBox_064"));
        checkBox_064->setGeometry(QRect(10, 120, 191, 23));
        checkBox_063 = new QCheckBox(tab_12);
        checkBox_063->setObjectName(QStringLiteral("checkBox_063"));
        checkBox_063->setGeometry(QRect(10, 100, 191, 23));
        checkBox_066 = new QCheckBox(tab_12);
        checkBox_066->setObjectName(QStringLiteral("checkBox_066"));
        checkBox_066->setGeometry(QRect(10, 160, 191, 23));
        checkBox_067 = new QCheckBox(tab_12);
        checkBox_067->setObjectName(QStringLiteral("checkBox_067"));
        checkBox_067->setGeometry(QRect(10, 180, 191, 23));
        checkBox_062 = new QCheckBox(tab_12);
        checkBox_062->setObjectName(QStringLiteral("checkBox_062"));
        checkBox_062->setGeometry(QRect(10, 80, 191, 23));
        checkBox_068 = new QCheckBox(tab_12);
        checkBox_068->setObjectName(QStringLiteral("checkBox_068"));
        checkBox_068->setGeometry(QRect(10, 200, 191, 23));
        checkBox_069 = new QCheckBox(tab_12);
        checkBox_069->setObjectName(QStringLiteral("checkBox_069"));
        checkBox_069->setGeometry(QRect(10, 220, 191, 23));
        checkBox_072 = new QCheckBox(tab_12);
        checkBox_072->setObjectName(QStringLiteral("checkBox_072"));
        checkBox_072->setGeometry(QRect(10, 280, 191, 23));
        checkBox_070 = new QCheckBox(tab_12);
        checkBox_070->setObjectName(QStringLiteral("checkBox_070"));
        checkBox_070->setGeometry(QRect(10, 240, 191, 23));
        checkBox_073 = new QCheckBox(tab_12);
        checkBox_073->setObjectName(QStringLiteral("checkBox_073"));
        checkBox_073->setGeometry(QRect(10, 300, 191, 23));
        checkBox_071 = new QCheckBox(tab_12);
        checkBox_071->setObjectName(QStringLiteral("checkBox_071"));
        checkBox_071->setGeometry(QRect(10, 260, 191, 23));
        checkBox_075 = new QCheckBox(tab_12);
        checkBox_075->setObjectName(QStringLiteral("checkBox_075"));
        checkBox_075->setGeometry(QRect(10, 340, 191, 23));
        checkBox_076 = new QCheckBox(tab_12);
        checkBox_076->setObjectName(QStringLiteral("checkBox_076"));
        checkBox_076->setGeometry(QRect(10, 360, 191, 23));
        checkBox_074 = new QCheckBox(tab_12);
        checkBox_074->setObjectName(QStringLiteral("checkBox_074"));
        checkBox_074->setGeometry(QRect(10, 320, 191, 23));
        checkBox_093 = new QCheckBox(tab_12);
        checkBox_093->setObjectName(QStringLiteral("checkBox_093"));
        checkBox_093->setGeometry(QRect(210, 320, 191, 23));
        checkBox_078 = new QCheckBox(tab_12);
        checkBox_078->setObjectName(QStringLiteral("checkBox_078"));
        checkBox_078->setGeometry(QRect(210, 20, 191, 23));
        checkBox_081 = new QCheckBox(tab_12);
        checkBox_081->setObjectName(QStringLiteral("checkBox_081"));
        checkBox_081->setGeometry(QRect(210, 80, 191, 23));
        checkBox_085 = new QCheckBox(tab_12);
        checkBox_085->setObjectName(QStringLiteral("checkBox_085"));
        checkBox_085->setGeometry(QRect(210, 160, 191, 23));
        checkBox_094 = new QCheckBox(tab_12);
        checkBox_094->setObjectName(QStringLiteral("checkBox_094"));
        checkBox_094->setGeometry(QRect(210, 340, 191, 23));
        checkBox_083 = new QCheckBox(tab_12);
        checkBox_083->setObjectName(QStringLiteral("checkBox_083"));
        checkBox_083->setGeometry(QRect(210, 120, 191, 23));
        checkBox_082 = new QCheckBox(tab_12);
        checkBox_082->setObjectName(QStringLiteral("checkBox_082"));
        checkBox_082->setGeometry(QRect(210, 100, 191, 23));
        checkBox_080 = new QCheckBox(tab_12);
        checkBox_080->setObjectName(QStringLiteral("checkBox_080"));
        checkBox_080->setGeometry(QRect(210, 60, 191, 23));
        checkBox_084 = new QCheckBox(tab_12);
        checkBox_084->setObjectName(QStringLiteral("checkBox_084"));
        checkBox_084->setGeometry(QRect(210, 140, 191, 23));
        checkBox_092 = new QCheckBox(tab_12);
        checkBox_092->setObjectName(QStringLiteral("checkBox_092"));
        checkBox_092->setGeometry(QRect(210, 300, 191, 23));
        checkBox_091 = new QCheckBox(tab_12);
        checkBox_091->setObjectName(QStringLiteral("checkBox_091"));
        checkBox_091->setGeometry(QRect(210, 280, 191, 23));
        checkBox_088 = new QCheckBox(tab_12);
        checkBox_088->setObjectName(QStringLiteral("checkBox_088"));
        checkBox_088->setGeometry(QRect(210, 220, 191, 23));
        checkBox_087 = new QCheckBox(tab_12);
        checkBox_087->setObjectName(QStringLiteral("checkBox_087"));
        checkBox_087->setGeometry(QRect(210, 200, 191, 23));
        checkBox_090 = new QCheckBox(tab_12);
        checkBox_090->setObjectName(QStringLiteral("checkBox_090"));
        checkBox_090->setGeometry(QRect(210, 260, 191, 23));
        checkBox_089 = new QCheckBox(tab_12);
        checkBox_089->setObjectName(QStringLiteral("checkBox_089"));
        checkBox_089->setGeometry(QRect(210, 240, 191, 23));
        checkBox_079 = new QCheckBox(tab_12);
        checkBox_079->setObjectName(QStringLiteral("checkBox_079"));
        checkBox_079->setGeometry(QRect(210, 40, 191, 23));
        checkBox_086 = new QCheckBox(tab_12);
        checkBox_086->setObjectName(QStringLiteral("checkBox_086"));
        checkBox_086->setGeometry(QRect(210, 180, 191, 23));
        checkBox_077 = new QCheckBox(tab_12);
        checkBox_077->setObjectName(QStringLiteral("checkBox_077"));
        checkBox_077->setGeometry(QRect(210, 0, 191, 23));
        checkBox_101 = new QCheckBox(tab_12);
        checkBox_101->setObjectName(QStringLiteral("checkBox_101"));
        checkBox_101->setGeometry(QRect(350, 20, 191, 23));
        checkBox_105 = new QCheckBox(tab_12);
        checkBox_105->setObjectName(QStringLiteral("checkBox_105"));
        checkBox_105->setGeometry(QRect(350, 100, 211, 23));
        checkBox_107 = new QCheckBox(tab_12);
        checkBox_107->setObjectName(QStringLiteral("checkBox_107"));
        checkBox_107->setGeometry(QRect(350, 140, 211, 23));
        checkBox_110 = new QCheckBox(tab_12);
        checkBox_110->setObjectName(QStringLiteral("checkBox_110"));
        checkBox_110->setGeometry(QRect(350, 200, 211, 23));
        checkBox_108 = new QCheckBox(tab_12);
        checkBox_108->setObjectName(QStringLiteral("checkBox_108"));
        checkBox_108->setGeometry(QRect(350, 160, 211, 23));
        checkBox_100 = new QCheckBox(tab_12);
        checkBox_100->setObjectName(QStringLiteral("checkBox_100"));
        checkBox_100->setGeometry(QRect(350, 0, 191, 23));
        checkBox_113 = new QCheckBox(tab_12);
        checkBox_113->setObjectName(QStringLiteral("checkBox_113"));
        checkBox_113->setGeometry(QRect(350, 260, 211, 23));
        checkBox_112 = new QCheckBox(tab_12);
        checkBox_112->setObjectName(QStringLiteral("checkBox_112"));
        checkBox_112->setGeometry(QRect(350, 240, 211, 23));
        checkBox_104 = new QCheckBox(tab_12);
        checkBox_104->setObjectName(QStringLiteral("checkBox_104"));
        checkBox_104->setGeometry(QRect(350, 80, 211, 23));
        checkBox_109 = new QCheckBox(tab_12);
        checkBox_109->setObjectName(QStringLiteral("checkBox_109"));
        checkBox_109->setGeometry(QRect(350, 180, 211, 23));
        checkBox_111 = new QCheckBox(tab_12);
        checkBox_111->setObjectName(QStringLiteral("checkBox_111"));
        checkBox_111->setGeometry(QRect(350, 220, 211, 23));
        checkBox_102 = new QCheckBox(tab_12);
        checkBox_102->setObjectName(QStringLiteral("checkBox_102"));
        checkBox_102->setGeometry(QRect(350, 40, 201, 23));
        checkBox_115 = new QCheckBox(tab_12);
        checkBox_115->setObjectName(QStringLiteral("checkBox_115"));
        checkBox_115->setGeometry(QRect(350, 300, 211, 23));
        checkBox_114 = new QCheckBox(tab_12);
        checkBox_114->setObjectName(QStringLiteral("checkBox_114"));
        checkBox_114->setGeometry(QRect(350, 280, 241, 23));
        checkBox_103 = new QCheckBox(tab_12);
        checkBox_103->setObjectName(QStringLiteral("checkBox_103"));
        checkBox_103->setGeometry(QRect(350, 60, 191, 23));
        checkBox_106 = new QCheckBox(tab_12);
        checkBox_106->setObjectName(QStringLiteral("checkBox_106"));
        checkBox_106->setGeometry(QRect(350, 120, 211, 23));
        checkBox_117 = new QCheckBox(tab_12);
        checkBox_117->setObjectName(QStringLiteral("checkBox_117"));
        checkBox_117->setGeometry(QRect(350, 320, 211, 23));
        checkBox_118 = new QCheckBox(tab_12);
        checkBox_118->setObjectName(QStringLiteral("checkBox_118"));
        checkBox_118->setGeometry(QRect(350, 360, 211, 23));
        checkBox_116 = new QCheckBox(tab_12);
        checkBox_116->setObjectName(QStringLiteral("checkBox_116"));
        checkBox_116->setGeometry(QRect(350, 340, 211, 23));
        tabWidget_2->addTab(tab_12, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        checkBox_132 = new QCheckBox(tab_5);
        checkBox_132->setObjectName(QStringLiteral("checkBox_132"));
        checkBox_132->setGeometry(QRect(10, 260, 161, 23));
        checkBox_130 = new QCheckBox(tab_5);
        checkBox_130->setObjectName(QStringLiteral("checkBox_130"));
        checkBox_130->setGeometry(QRect(10, 220, 161, 23));
        checkBox_120 = new QCheckBox(tab_5);
        checkBox_120->setObjectName(QStringLiteral("checkBox_120"));
        checkBox_120->setGeometry(QRect(10, 20, 211, 23));
        checkBox_123 = new QCheckBox(tab_5);
        checkBox_123->setObjectName(QStringLiteral("checkBox_123"));
        checkBox_123->setGeometry(QRect(10, 80, 191, 23));
        checkBox_122 = new QCheckBox(tab_5);
        checkBox_122->setObjectName(QStringLiteral("checkBox_122"));
        checkBox_122->setGeometry(QRect(10, 60, 191, 23));
        checkBox_121 = new QCheckBox(tab_5);
        checkBox_121->setObjectName(QStringLiteral("checkBox_121"));
        checkBox_121->setGeometry(QRect(10, 40, 191, 23));
        checkBox_126 = new QCheckBox(tab_5);
        checkBox_126->setObjectName(QStringLiteral("checkBox_126"));
        checkBox_126->setGeometry(QRect(10, 140, 191, 23));
        checkBox_125 = new QCheckBox(tab_5);
        checkBox_125->setObjectName(QStringLiteral("checkBox_125"));
        checkBox_125->setGeometry(QRect(10, 120, 191, 23));
        checkBox_124 = new QCheckBox(tab_5);
        checkBox_124->setObjectName(QStringLiteral("checkBox_124"));
        checkBox_124->setGeometry(QRect(10, 100, 191, 23));
        checkBox_119 = new QCheckBox(tab_5);
        checkBox_119->setObjectName(QStringLiteral("checkBox_119"));
        checkBox_119->setGeometry(QRect(10, 0, 211, 23));
        checkBox_133 = new QCheckBox(tab_5);
        checkBox_133->setObjectName(QStringLiteral("checkBox_133"));
        checkBox_133->setGeometry(QRect(10, 280, 161, 23));
        checkBox_134 = new QCheckBox(tab_5);
        checkBox_134->setObjectName(QStringLiteral("checkBox_134"));
        checkBox_134->setGeometry(QRect(10, 300, 161, 23));
        checkBox_135 = new QCheckBox(tab_5);
        checkBox_135->setObjectName(QStringLiteral("checkBox_135"));
        checkBox_135->setGeometry(QRect(10, 320, 161, 23));
        checkBox_136 = new QCheckBox(tab_5);
        checkBox_136->setObjectName(QStringLiteral("checkBox_136"));
        checkBox_136->setGeometry(QRect(10, 340, 161, 23));
        checkBox_137 = new QCheckBox(tab_5);
        checkBox_137->setObjectName(QStringLiteral("checkBox_137"));
        checkBox_137->setGeometry(QRect(10, 360, 161, 23));
        checkBox_138 = new QCheckBox(tab_5);
        checkBox_138->setObjectName(QStringLiteral("checkBox_138"));
        checkBox_138->setGeometry(QRect(210, 0, 161, 23));
        checkBox_139 = new QCheckBox(tab_5);
        checkBox_139->setObjectName(QStringLiteral("checkBox_139"));
        checkBox_139->setGeometry(QRect(210, 20, 161, 23));
        checkBox_140 = new QCheckBox(tab_5);
        checkBox_140->setObjectName(QStringLiteral("checkBox_140"));
        checkBox_140->setGeometry(QRect(210, 40, 161, 23));
        checkBox_141 = new QCheckBox(tab_5);
        checkBox_141->setObjectName(QStringLiteral("checkBox_141"));
        checkBox_141->setGeometry(QRect(210, 60, 161, 23));
        checkBox_142 = new QCheckBox(tab_5);
        checkBox_142->setObjectName(QStringLiteral("checkBox_142"));
        checkBox_142->setGeometry(QRect(210, 80, 161, 23));
        checkBox_143 = new QCheckBox(tab_5);
        checkBox_143->setObjectName(QStringLiteral("checkBox_143"));
        checkBox_143->setGeometry(QRect(210, 100, 161, 23));
        checkBox_144 = new QCheckBox(tab_5);
        checkBox_144->setObjectName(QStringLiteral("checkBox_144"));
        checkBox_144->setGeometry(QRect(210, 120, 161, 23));
        checkBox_145 = new QCheckBox(tab_5);
        checkBox_145->setObjectName(QStringLiteral("checkBox_145"));
        checkBox_145->setGeometry(QRect(210, 140, 161, 23));
        checkBox_146 = new QCheckBox(tab_5);
        checkBox_146->setObjectName(QStringLiteral("checkBox_146"));
        checkBox_146->setGeometry(QRect(210, 160, 161, 23));
        checkBox_147 = new QCheckBox(tab_5);
        checkBox_147->setObjectName(QStringLiteral("checkBox_147"));
        checkBox_147->setGeometry(QRect(210, 180, 161, 23));
        checkBox_148 = new QCheckBox(tab_5);
        checkBox_148->setObjectName(QStringLiteral("checkBox_148"));
        checkBox_148->setGeometry(QRect(210, 200, 161, 23));
        checkBox_149 = new QCheckBox(tab_5);
        checkBox_149->setObjectName(QStringLiteral("checkBox_149"));
        checkBox_149->setGeometry(QRect(210, 220, 161, 23));
        checkBox_131 = new QCheckBox(tab_5);
        checkBox_131->setObjectName(QStringLiteral("checkBox_131"));
        checkBox_131->setGeometry(QRect(10, 240, 181, 23));
        checkBox_127 = new QCheckBox(tab_5);
        checkBox_127->setObjectName(QStringLiteral("checkBox_127"));
        checkBox_127->setGeometry(QRect(10, 160, 191, 23));
        checkBox_128 = new QCheckBox(tab_5);
        checkBox_128->setObjectName(QStringLiteral("checkBox_128"));
        checkBox_128->setGeometry(QRect(10, 180, 191, 23));
        checkBox_129 = new QCheckBox(tab_5);
        checkBox_129->setObjectName(QStringLiteral("checkBox_129"));
        checkBox_129->setGeometry(QRect(10, 200, 191, 23));
        checkBox_150 = new QCheckBox(tab_5);
        checkBox_150->setObjectName(QStringLiteral("checkBox_150"));
        checkBox_150->setGeometry(QRect(210, 240, 161, 23));
        tabWidget_2->addTab(tab_5, QString());
        tabWidget->addTab(tab_4, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tabWidget_3 = new QTabWidget(tab_3);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(0, 0, 691, 431));
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        label_66 = new QLabel(tab_6);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(250, 360, 141, 31));
        QFont font;
        font.setBold(false);
        font.setWeight(50);
        label_66->setFont(font);
        doInvisibleAsterisksButton = new QPushButton(tab_6);
        doInvisibleAsterisksButton->setObjectName(QStringLiteral("doInvisibleAsterisksButton"));
        doInvisibleAsterisksButton->setGeometry(QRect(10, 180, 221, 36));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/images/kernel.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        doInvisibleAsterisksButton->setIcon(icon7);
        doInvisibleAsterisksButton->setIconSize(QSize(30, 30));
        doInvisibleAsterisksButton->setCheckable(false);
        label_67 = new QLabel(tab_6);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(250, 320, 141, 31));
        label_67->setFont(font);
        label_6 = new QLabel(tab_6);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 120, 141, 16));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        label_6->setFont(font1);
        label_63 = new QLabel(tab_6);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(250, 140, 201, 31));
        label_63->setFont(font);
        label_8 = new QLabel(tab_6);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 300, 141, 16));
        label_8->setFont(font1);
        label_7 = new QLabel(tab_6);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 230, 141, 16));
        label_7->setFont(font1);
        openSourcesListDButton = new QPushButton(tab_6);
        openSourcesListDButton->setObjectName(QStringLiteral("openSourcesListDButton"));
        openSourcesListDButton->setGeometry(QRect(10, 250, 221, 36));
        openSourcesListDButton->setIcon(icon7);
        openSourcesListDButton->setIconSize(QSize(30, 30));
        openSourcesListDButton->setCheckable(false);
        label_64 = new QLabel(tab_6);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(250, 180, 201, 31));
        label_64->setFont(font);
        disableHibernationButton = new QPushButton(tab_6);
        disableHibernationButton->setObjectName(QStringLiteral("disableHibernationButton"));
        disableHibernationButton->setGeometry(QRect(10, 360, 221, 36));
        disableHibernationButton->setIcon(icon7);
        disableHibernationButton->setIconSize(QSize(30, 30));
        disableHibernationButton->setCheckable(false);
        doVisibleAsterisksButton = new QPushButton(tab_6);
        doVisibleAsterisksButton->setObjectName(QStringLiteral("doVisibleAsterisksButton"));
        doVisibleAsterisksButton->setGeometry(QRect(10, 140, 221, 36));
        doVisibleAsterisksButton->setIcon(icon7);
        doVisibleAsterisksButton->setIconSize(QSize(30, 30));
        doVisibleAsterisksButton->setCheckable(false);
        label_65 = new QLabel(tab_6);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(250, 250, 221, 31));
        label_65->setFont(font);
        enableHibernationButton = new QPushButton(tab_6);
        enableHibernationButton->setObjectName(QStringLiteral("enableHibernationButton"));
        enableHibernationButton->setGeometry(QRect(10, 320, 221, 36));
        enableHibernationButton->setIcon(icon7);
        enableHibernationButton->setIconSize(QSize(30, 30));
        enableHibernationButton->setCheckable(false);
        label_68 = new QLabel(tab_6);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(250, 40, 431, 41));
        label_68->setFont(font);
        enableSudoWithoutPassButton = new QPushButton(tab_6);
        enableSudoWithoutPassButton->setObjectName(QStringLiteral("enableSudoWithoutPassButton"));
        enableSudoWithoutPassButton->setGeometry(QRect(10, 30, 221, 36));
        enableSudoWithoutPassButton->setIcon(icon7);
        enableSudoWithoutPassButton->setIconSize(QSize(30, 30));
        enableSudoWithoutPassButton->setCheckable(false);
        disableSudoWithoutPassButton = new QPushButton(tab_6);
        disableSudoWithoutPassButton->setObjectName(QStringLiteral("disableSudoWithoutPassButton"));
        disableSudoWithoutPassButton->setGeometry(QRect(10, 70, 221, 36));
        disableSudoWithoutPassButton->setIcon(icon7);
        disableSudoWithoutPassButton->setIconSize(QSize(30, 30));
        disableSudoWithoutPassButton->setCheckable(false);
        label_10 = new QLabel(tab_6);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 10, 151, 16));
        label_10->setFont(font1);
        openSudoersFileButton = new QPushButton(tab_6);
        openSudoersFileButton->setObjectName(QStringLiteral("openSudoersFileButton"));
        openSudoersFileButton->setGeometry(QRect(420, 30, 221, 36));
        openSudoersFileButton->setIcon(icon7);
        openSudoersFileButton->setIconSize(QSize(30, 30));
        openSudoersFileButton->setCheckable(false);
        backupSudoersFileButton = new QPushButton(tab_6);
        backupSudoersFileButton->setObjectName(QStringLiteral("backupSudoersFileButton"));
        backupSudoersFileButton->setGeometry(QRect(420, 70, 221, 36));
        backupSudoersFileButton->setIcon(icon7);
        backupSudoersFileButton->setIconSize(QSize(30, 30));
        backupSudoersFileButton->setCheckable(false);
        tabWidget_3->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        installTemplatesButton = new QPushButton(tab_7);
        installTemplatesButton->setObjectName(QStringLiteral("installTemplatesButton"));
        installTemplatesButton->setGeometry(QRect(10, 30, 221, 36));
        installTemplatesButton->setIcon(icon7);
        installTemplatesButton->setIconSize(QSize(30, 30));
        installTemplatesButton->setCheckable(false);
        label_62 = new QLabel(tab_7);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(250, 40, 251, 21));
        label_62->setFont(font);
        label_5 = new QLabel(tab_7);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 10, 141, 16));
        label_5->setFont(font1);
        tabWidget_3->addTab(tab_7, QString());
        tabWidget->addTab(tab_3, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        toolBox = new QToolBox(tab);
        toolBox->setObjectName(QStringLiteral("toolBox"));
        toolBox->setEnabled(true);
        toolBox->setGeometry(QRect(10, 10, 631, 371));
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        page_3->setGeometry(QRect(0, 0, 631, 287));
        label_61 = new QLabel(page_3);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(250, 20, 141, 21));
        label_61->setFont(font);
        upgradeLatestDevButton = new QPushButton(page_3);
        upgradeLatestDevButton->setObjectName(QStringLiteral("upgradeLatestDevButton"));
        upgradeLatestDevButton->setGeometry(QRect(10, 10, 221, 36));
        upgradeLatestDevButton->setIcon(icon7);
        upgradeLatestDevButton->setIconSize(QSize(30, 30));
        upgradeLatestDevButton->setCheckable(false);
        toolBox->addItem(page_3, QStringLiteral("Developer"));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        page->setGeometry(QRect(0, 0, 631, 287));
        dist_upgradeButton = new QPushButton(page);
        dist_upgradeButton->setObjectName(QStringLiteral("dist_upgradeButton"));
        dist_upgradeButton->setGeometry(QRect(10, 10, 221, 36));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/images/flecha_arriba.png"), QSize(), QIcon::Normal, QIcon::Off);
        dist_upgradeButton->setIcon(icon8);
        dist_upgradeButton->setIconSize(QSize(30, 30));
        dist_upgradeButton->setCheckable(false);
        label_17 = new QLabel(page);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(250, 10, 281, 41));
        label_17->setFont(font);
        cleanKernelsButton = new QPushButton(page);
        cleanKernelsButton->setObjectName(QStringLiteral("cleanKernelsButton"));
        cleanKernelsButton->setGeometry(QRect(10, 60, 221, 36));
        cleanKernelsButton->setIcon(icon7);
        cleanKernelsButton->setIconSize(QSize(30, 30));
        cleanKernelsButton->setCheckable(false);
        label_59 = new QLabel(page);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(250, 70, 221, 21));
        label_59->setFont(font);
        label_60 = new QLabel(page);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(250, 120, 131, 21));
        label_60->setFont(font);
        upgradeLatestStableButton = new QPushButton(page);
        upgradeLatestStableButton->setObjectName(QStringLiteral("upgradeLatestStableButton"));
        upgradeLatestStableButton->setGeometry(QRect(10, 110, 221, 36));
        upgradeLatestStableButton->setIcon(icon7);
        upgradeLatestStableButton->setIconSize(QSize(30, 30));
        upgradeLatestStableButton->setCheckable(false);
        toolBox->addItem(page, QStringLiteral("Advanced user"));
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        page_2->setGeometry(QRect(0, 0, 631, 287));
        cleanButton = new QPushButton(page_2);
        cleanButton->setObjectName(QStringLiteral("cleanButton"));
        cleanButton->setGeometry(QRect(10, 210, 271, 36));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/images/escoba.png"), QSize(), QIcon::Normal, QIcon::Off);
        cleanButton->setIcon(icon9);
        cleanButton->setIconSize(QSize(30, 30));
        cleanButton->setCheckable(false);
        updateAndUpgradeButton = new QPushButton(page_2);
        updateAndUpgradeButton->setObjectName(QStringLiteral("updateAndUpgradeButton"));
        updateAndUpgradeButton->setGeometry(QRect(10, 10, 271, 36));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/images/upgrade.png"), QSize(), QIcon::Normal, QIcon::Off);
        updateAndUpgradeButton->setIcon(icon10);
        updateAndUpgradeButton->setIconSize(QSize(30, 30));
        updateAndUpgradeButton->setCheckable(false);
        basicPackagesInstallButton = new QPushButton(page_2);
        basicPackagesInstallButton->setObjectName(QStringLiteral("basicPackagesInstallButton"));
        basicPackagesInstallButton->setGeometry(QRect(10, 160, 271, 40));
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/images/install.png"), QSize(), QIcon::Normal, QIcon::Off);
        basicPackagesInstallButton->setIcon(icon11);
        basicPackagesInstallButton->setIconSize(QSize(30, 30));
        basicPackagesInstallButton->setCheckable(false);
        updateReposButton = new QPushButton(page_2);
        updateReposButton->setObjectName(QStringLiteral("updateReposButton"));
        updateReposButton->setEnabled(true);
        updateReposButton->setGeometry(QRect(10, 60, 271, 36));
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/images/update.png"), QSize(), QIcon::Normal, QIcon::Off);
        updateReposButton->setIcon(icon12);
        updateReposButton->setIconSize(QSize(30, 30));
        updateReposButton->setCheckable(false);
        label_14 = new QLabel(page_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(290, 70, 251, 16));
        label_14->setFont(font);
        label_15 = new QLabel(page_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(290, 10, 251, 31));
        label_15->setFont(font);
        label_16 = new QLabel(page_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(290, 200, 161, 61));
        label_16->setFont(font);
        label_31 = new QLabel(page_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(290, 120, 251, 16));
        label_31->setFont(font);
        upgradeReposButton = new QPushButton(page_2);
        upgradeReposButton->setObjectName(QStringLiteral("upgradeReposButton"));
        upgradeReposButton->setEnabled(true);
        upgradeReposButton->setGeometry(QRect(10, 110, 271, 36));
        upgradeReposButton->setIcon(icon12);
        upgradeReposButton->setIconSize(QSize(30, 30));
        upgradeReposButton->setCheckable(false);
        label_25 = new QLabel(page_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(290, 150, 321, 51));
        label_25->setFont(font);
        toolBox->addItem(page_2, QStringLiteral("Normal user"));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        integrityCheckButton = new QPushButton(tab_2);
        integrityCheckButton->setObjectName(QStringLiteral("integrityCheckButton"));
        integrityCheckButton->setGeometry(QRect(10, 40, 40, 36));
        integrityCheckButton->setMaximumSize(QSize(40, 40));
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/images/repair.png"), QSize(), QIcon::Normal, QIcon::Off);
        integrityCheckButton->setIcon(icon13);
        integrityCheckButton->setIconSize(QSize(30, 30));
        integrityCheckButton->setCheckable(false);
        label_2 = new QLabel(tab_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 10, 331, 16));
        label_2->setFont(font1);
        label_3 = new QLabel(tab_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 100, 431, 16));
        label_3->setFont(font1);
        fixBrokenPackagesButton_1 = new QPushButton(tab_2);
        fixBrokenPackagesButton_1->setObjectName(QStringLiteral("fixBrokenPackagesButton_1"));
        fixBrokenPackagesButton_1->setGeometry(QRect(10, 130, 40, 36));
        fixBrokenPackagesButton_1->setMaximumSize(QSize(40, 40));
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/images/red-number-1.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_1->setIcon(icon14);
        fixBrokenPackagesButton_1->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_1->setCheckable(false);
        fixBrokenPackagesButton_2 = new QPushButton(tab_2);
        fixBrokenPackagesButton_2->setObjectName(QStringLiteral("fixBrokenPackagesButton_2"));
        fixBrokenPackagesButton_2->setGeometry(QRect(10, 170, 40, 36));
        fixBrokenPackagesButton_2->setMaximumSize(QSize(40, 40));
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/images/red-number-2.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_2->setIcon(icon15);
        fixBrokenPackagesButton_2->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_2->setCheckable(false);
        fixBrokenPackagesButton_3 = new QPushButton(tab_2);
        fixBrokenPackagesButton_3->setObjectName(QStringLiteral("fixBrokenPackagesButton_3"));
        fixBrokenPackagesButton_3->setGeometry(QRect(10, 210, 40, 36));
        fixBrokenPackagesButton_3->setMaximumSize(QSize(40, 40));
        QIcon icon16;
        icon16.addFile(QStringLiteral(":/images/red-number-3.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_3->setIcon(icon16);
        fixBrokenPackagesButton_3->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_3->setCheckable(false);
        fixBrokenPackagesButton_4 = new QPushButton(tab_2);
        fixBrokenPackagesButton_4->setObjectName(QStringLiteral("fixBrokenPackagesButton_4"));
        fixBrokenPackagesButton_4->setGeometry(QRect(10, 250, 40, 36));
        fixBrokenPackagesButton_4->setMaximumSize(QSize(40, 40));
        QIcon icon17;
        icon17.addFile(QStringLiteral(":/images/red-number-4.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_4->setIcon(icon17);
        fixBrokenPackagesButton_4->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_4->setCheckable(false);
        fixBrokenPackagesButton_5 = new QPushButton(tab_2);
        fixBrokenPackagesButton_5->setObjectName(QStringLiteral("fixBrokenPackagesButton_5"));
        fixBrokenPackagesButton_5->setGeometry(QRect(10, 290, 40, 36));
        fixBrokenPackagesButton_5->setMaximumSize(QSize(40, 40));
        QIcon icon18;
        icon18.addFile(QStringLiteral(":/images/red-number-5.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_5->setIcon(icon18);
        fixBrokenPackagesButton_5->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_5->setCheckable(false);
        fixBrokenPackagesButton_6 = new QPushButton(tab_2);
        fixBrokenPackagesButton_6->setObjectName(QStringLiteral("fixBrokenPackagesButton_6"));
        fixBrokenPackagesButton_6->setGeometry(QRect(10, 330, 40, 36));
        fixBrokenPackagesButton_6->setMaximumSize(QSize(40, 40));
        QIcon icon19;
        icon19.addFile(QStringLiteral(":/images/red-number-6.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_6->setIcon(icon19);
        fixBrokenPackagesButton_6->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_6->setCheckable(false);
        label_18 = new QLabel(tab_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(60, 50, 111, 16));
        label_18->setFont(font);
        label_19 = new QLabel(tab_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(60, 140, 261, 16));
        label_19->setFont(font);
        label_20 = new QLabel(tab_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(60, 180, 251, 16));
        label_20->setFont(font);
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(60, 220, 281, 16));
        label_21->setFont(font);
        label_22 = new QLabel(tab_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(60, 250, 491, 31));
        label_22->setFont(font);
        label_23 = new QLabel(tab_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(60, 300, 251, 16));
        label_23->setFont(font);
        label_24 = new QLabel(tab_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(60, 340, 331, 16));
        label_24->setFont(font);
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(350, 10, 111, 16));
        label_9->setFont(font1);
        repairNetworkButton = new QPushButton(tab_2);
        repairNetworkButton->setObjectName(QStringLiteral("repairNetworkButton"));
        repairNetworkButton->setGeometry(QRect(350, 40, 40, 36));
        repairNetworkButton->setMaximumSize(QSize(40, 40));
        repairNetworkButton->setIcon(icon13);
        repairNetworkButton->setIconSize(QSize(30, 30));
        repairNetworkButton->setCheckable(false);
        label_27 = new QLabel(tab_2);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(400, 50, 231, 16));
        label_27->setFont(font);
        repairGPGKeys = new QPushButton(tab_2);
        repairGPGKeys->setObjectName(QStringLiteral("repairGPGKeys"));
        repairGPGKeys->setGeometry(QRect(350, 170, 40, 36));
        repairGPGKeys->setMaximumSize(QSize(40, 40));
        repairGPGKeys->setIcon(icon13);
        repairGPGKeys->setIconSize(QSize(30, 30));
        repairGPGKeys->setCheckable(false);
        label_28 = new QLabel(tab_2);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(400, 180, 151, 16));
        label_28->setFont(font);
        label_29 = new QLabel(tab_2);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(350, 140, 171, 16));
        label_29->setFont(font1);
        label_30 = new QLabel(tab_2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(60, 30, 241, 16));
        label_30->setFont(font1);
        tabWidget->addTab(tab_2, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 711, 19));
        menuNuevo = new QMenu(menuBar);
        menuNuevo->setObjectName(QStringLiteral("menuNuevo"));
        menuEdici_n = new QMenu(menuBar);
        menuEdici_n->setObjectName(QStringLiteral("menuEdici_n"));
        menuAyuda = new QMenu(menuBar);
        menuAyuda->setObjectName(QStringLiteral("menuAyuda"));
        MainWindow->setMenuBar(menuBar);
        fileToolBar = new QToolBar(MainWindow);
        fileToolBar->setObjectName(QStringLiteral("fileToolBar"));
        fileToolBar->setEnabled(false);
        fileToolBar->setMovable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, fileToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        editToolBar = new QToolBar(MainWindow);
        editToolBar->setObjectName(QStringLiteral("editToolBar"));
        editToolBar->setEnabled(false);
        editToolBar->setMovable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, editToolBar);

        menuBar->addAction(menuNuevo->menuAction());
        menuBar->addAction(menuEdici_n->menuAction());
        menuBar->addAction(menuAyuda->menuAction());
        menuNuevo->addSeparator();
        menuNuevo->addAction(actionNew);
        menuNuevo->addAction(actionOpen);
        menuNuevo->addAction(actionSave);
        menuNuevo->addAction(actionSave_as);
        menuNuevo->addSeparator();
        menuNuevo->addAction(actionExit);
        menuEdici_n->addAction(actionCopy);
        menuEdici_n->addAction(actionCut);
        menuEdici_n->addAction(actionPaste);
        menuAyuda->addAction(actionAbout);
        menuAyuda->addAction(actionAbout_Qt);
        fileToolBar->addAction(actionNew);
        fileToolBar->addAction(actionSave);
        editToolBar->addAction(actionCut);
        editToolBar->addAction(actionCopy);
        editToolBar->addAction(actionPaste);

        retranslateUi(MainWindow);
        QObject::connect(actionExit, SIGNAL(triggered()), MainWindow, SLOT(close()));

        tabWidget->setCurrentIndex(3);
        tabWidget_2->setCurrentIndex(0);
        tabWidget_3->setCurrentIndex(0);
        toolBox->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "ubunsys", 0));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0));
        actionPaste->setText(QApplication::translate("MainWindow", "Paste", 0));
        actionAbout->setText(QApplication::translate("MainWindow", "About", 0));
        actionAbout_Qt->setText(QApplication::translate("MainWindow", "About Qt", 0));
        actionSave_as->setText(QApplication::translate("MainWindow", "Save as...", 0));
        actionNew->setText(QApplication::translate("MainWindow", "New", 0));
        actionOpen->setText(QApplication::translate("MainWindow", "Open", 0));
        actionSave->setText(QApplication::translate("MainWindow", "Save", 0));
        actionCopy->setText(QApplication::translate("MainWindow", "Copy", 0));
        actionCut->setText(QApplication::translate("MainWindow", "Cut", 0));
        actionCut->setIconText(QApplication::translate("MainWindow", "Cortar", 0));
        unselectAllButton->setText(QApplication::translate("MainWindow", "Unselect All", 0));
        selectAllButton->setText(QApplication::translate("MainWindow", "Select All", 0));
        installSelectedPackagesButton->setText(QApplication::translate("MainWindow", "Install", 0));
        uninstallSelectedPackagesButton->setText(QApplication::translate("MainWindow", "Uninstall", 0));
        loadSelectionButton->setText(QApplication::translate("MainWindow", "Load", 0));
        saveSelectionButton->setText(QApplication::translate("MainWindow", "Save", 0));
        checkBox_012->setText(QApplication::translate("MainWindow", "012.keepassx", 0));
        checkBox_013->setText(QApplication::translate("MainWindow", "013.ubuntu-restricted-extras", 0));
        checkBox_014->setText(QApplication::translate("MainWindow", "014.ttf-ancient fonts", 0));
        checkBox_009->setText(QApplication::translate("MainWindow", "009.xorg-edgers", 0));
        checkBox_011->setText(QApplication::translate("MainWindow", "011.graphics-drivers-team", 0));
        checkBox_020->setText(QApplication::translate("MainWindow", "020.gnome-disk-utility", 0));
        checkBox_010->setText(QApplication::translate("MainWindow", "010.oibaf", 0));
        checkBox_021->setText(QApplication::translate("MainWindow", "021.gparted", 0));
        checkBox_008->setText(QApplication::translate("MainWindow", "008.mtp-support", 0));
        checkBox_015->setText(QApplication::translate("MainWindow", "015.synaptic", 0));
        checkBox_005->setText(QApplication::translate("MainWindow", "005.y-ppa-manager", 0));
        checkBox_016->setText(QApplication::translate("MainWindow", "016.preload", 0));
        checkBox_017->setText(QApplication::translate("MainWindow", "017.prelink", 0));
        checkBox_018->setText(QApplication::translate("MainWindow", "018.gdebi", 0));
        checkBox_004->setText(QApplication::translate("MainWindow", "004.apt-fast", 0));
        checkBox_006->setText(QApplication::translate("MainWindow", "006.getdeb", 0));
        checkBox_022->setText(QApplication::translate("MainWindow", "022.gkrellm", 0));
        checkBox_007->setText(QApplication::translate("MainWindow", "007.playdeb", 0));
        checkBox_023->setText(QApplication::translate("MainWindow", "023.mate-tweak", 0));
        checkBox_024->setText(QApplication::translate("MainWindow", "024.recoll", 0));
        checkBox_025->setText(QApplication::translate("MainWindow", "025.brasero", 0));
        checkBox_026->setText(QApplication::translate("MainWindow", "026.k3b", 0));
        checkBox_027->setText(QApplication::translate("MainWindow", "027.gtkorphan", 0));
        checkBox_028->setText(QApplication::translate("MainWindow", "028.byobu", 0));
        checkBox_029->setText(QApplication::translate("MainWindow", "029.gsmartcontrol", 0));
        checkBox_030->setText(QApplication::translate("MainWindow", "030.software-center", 0));
        checkBox_031->setText(QApplication::translate("MainWindow", "031.gnome-software", 0));
        checkBox_032->setText(QApplication::translate("MainWindow", "032.test", 0));
        checkBox_033->setText(QApplication::translate("MainWindow", "033.appgrid", 0));
        checkBox_034->setText(QApplication::translate("MainWindow", "034.mintStick", 0));
        checkBox_035->setText(QApplication::translate("MainWindow", "035.mate-dock-applet", 0));
        checkBox_036->setText(QApplication::translate("MainWindow", "036.extundelete", 0));
        checkBox_037->setText(QApplication::translate("MainWindow", "037.cairo-dock", 0));
        checkBox_046->setText(QApplication::translate("MainWindow", "046.clipit", 0));
        checkBox_045->setText(QApplication::translate("MainWindow", "045.bleachbit", 0));
        checkBox_044->setText(QApplication::translate("MainWindow", "044.grub-customizer", 0));
        checkBox_043->setText(QApplication::translate("MainWindow", "043.synapse", 0));
        checkBox_042->setText(QApplication::translate("MainWindow", "042.converseen", 0));
        checkBox_047->setText(QApplication::translate("MainWindow", "047.screenfetch", 0));
        checkBox_048->setText(QApplication::translate("MainWindow", "048.i-nex", 0));
        checkBox_049->setText(QApplication::translate("MainWindow", "049.ANGRYsearch", 0));
        checkBox_050->setText(QApplication::translate("MainWindow", "050.fish-shell", 0));
        checkBox_051->setText(QApplication::translate("MainWindow", "051.furiusisomount", 0));
        checkBox_052->setText(QApplication::translate("MainWindow", "052.ddrescue-gui", 0));
        checkBox_053->setText(QApplication::translate("MainWindow", "053.unetbootin", 0));
        checkBox_054->setText(QApplication::translate("MainWindow", "054.manpages-es", 0));
        checkBox_055->setText(QApplication::translate("MainWindow", "055.asterisk-on-cli-passwords", 0));
        checkBox_056->setText(QApplication::translate("MainWindow", "056.disable-system-crash-reports", 0));
        checkBox_041->setText(QApplication::translate("MainWindow", "041.teamviewer", 0));
        checkBox_038->setText(QApplication::translate("MainWindow", "038.ubuntu-after-install", 0));
        checkBox_040->setText(QApplication::translate("MainWindow", "040.postinstallerf", 0));
        checkBox_039->setText(QApplication::translate("MainWindow", "039.ubutricks", 0));
        checkBox_003->setText(QApplication::translate("MainWindow", "003.megasync", 0));
        checkBox_001->setText(QApplication::translate("MainWindow", "001.freefilesync", 0));
        checkBox_002->setText(QApplication::translate("MainWindow", "002.dropbox", 0));
        checkBox_019->setText(QApplication::translate("MainWindow", "019.ppa-purge", 0));
        checkBox_057->setText(QApplication::translate("MainWindow", "057.vibrancy-colors", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_11), QApplication::translate("MainWindow", "Tab 1", 0));
        checkBox_058->setText(QApplication::translate("MainWindow", "058.flatabulous-theme", 0));
        checkBox_060->setText(QApplication::translate("MainWindow", "060.myspell", 0));
        checkBox_059->setText(QApplication::translate("MainWindow", "059.aspell", 0));
        checkBox_061->setText(QApplication::translate("MainWindow", "061.gufw", 0));
        checkBox_065->setText(QApplication::translate("MainWindow", "065.gnome-exe-thumbnailer", 0));
        checkBox_064->setText(QApplication::translate("MainWindow", "064.krita-testing", 0));
        checkBox_063->setText(QApplication::translate("MainWindow", "063.gimp-edge", 0));
        checkBox_066->setText(QApplication::translate("MainWindow", "066.shutter", 0));
        checkBox_067->setText(QApplication::translate("MainWindow", "067.inkscape-stable", 0));
        checkBox_062->setText(QApplication::translate("MainWindow", "062.gimp", 0));
        checkBox_068->setText(QApplication::translate("MainWindow", "068.inkscape-trunk", 0));
        checkBox_069->setText(QApplication::translate("MainWindow", "069.qmmp", 0));
        checkBox_072->setText(QApplication::translate("MainWindow", "072.smplayer", 0));
        checkBox_070->setText(QApplication::translate("MainWindow", "070.kazam", 0));
        checkBox_073->setText(QApplication::translate("MainWindow", "073.handbrake", 0));
        checkBox_071->setText(QApplication::translate("MainWindow", "071.sopcast", 0));
        checkBox_075->setText(QApplication::translate("MainWindow", "075.vlc-stable", 0));
        checkBox_076->setText(QApplication::translate("MainWindow", "076.vlc-daily", 0));
        checkBox_074->setText(QApplication::translate("MainWindow", "074.ffmpeg", 0));
        checkBox_093->setText(QApplication::translate("MainWindow", "093.Qt-Linux", 0));
        checkBox_078->setText(QApplication::translate("MainWindow", "078.openjdk-8", 0));
        checkBox_081->setText(QApplication::translate("MainWindow", "081.dev-utils", 0));
        checkBox_085->setText(QApplication::translate("MainWindow", "085.dia", 0));
        checkBox_094->setText(QApplication::translate("MainWindow", "094.kicad", 0));
        checkBox_083->setText(QApplication::translate("MainWindow", "083.smartgit", 0));
        checkBox_082->setText(QApplication::translate("MainWindow", "082.git-stable", 0));
        checkBox_080->setText(QApplication::translate("MainWindow", "080.meld", 0));
        checkBox_084->setText(QApplication::translate("MainWindow", "084.flatpak", 0));
        checkBox_092->setText(QApplication::translate("MainWindow", "092.git-gui", 0));
        checkBox_091->setText(QApplication::translate("MainWindow", "091.git-rc", 0));
        checkBox_088->setText(QApplication::translate("MainWindow", "088.uecide", 0));
        checkBox_087->setText(QApplication::translate("MainWindow", "087.fritzing", 0));
        checkBox_090->setText(QApplication::translate("MainWindow", "090.arduino-studio", 0));
        checkBox_089->setText(QApplication::translate("MainWindow", "089.arduino-ide", 0));
        checkBox_079->setText(QApplication::translate("MainWindow", "079.openjdk-7", 0));
        checkBox_086->setText(QApplication::translate("MainWindow", "086.blender", 0));
        checkBox_077->setText(QApplication::translate("MainWindow", "077.notepadqq", 0));
        checkBox_101->setText(QApplication::translate("MainWindow", "101.google-chrome-stable", 0));
        checkBox_105->setText(QApplication::translate("MainWindow", "105.firefox-trunk", 0));
        checkBox_107->setText(QApplication::translate("MainWindow", "107.pepper-flash-for-chromium", 0));
        checkBox_110->setText(QApplication::translate("MainWindow", "110.skype", 0));
        checkBox_108->setText(QApplication::translate("MainWindow", "108.pepper-flash-for-firefox", 0));
        checkBox_100->setText(QApplication::translate("MainWindow", "100.vivaldi-browser", 0));
        checkBox_113->setText(QApplication::translate("MainWindow", "113.telegram", 0));
        checkBox_112->setText(QApplication::translate("MainWindow", "112.wire", 0));
        checkBox_104->setText(QApplication::translate("MainWindow", "104.firefox", 0));
        checkBox_109->setText(QApplication::translate("MainWindow", "109.tor-browser", 0));
        checkBox_111->setText(QApplication::translate("MainWindow", "111.mumble", 0));
        checkBox_102->setText(QApplication::translate("MainWindow", "102.google-chrome-unstable", 0));
        checkBox_115->setText(QApplication::translate("MainWindow", "115.Whatsie", 0));
        checkBox_114->setText(QApplication::translate("MainWindow", "114.Facebook-Messenger-Desktop", 0));
        checkBox_103->setText(QApplication::translate("MainWindow", "103.chromium", 0));
        checkBox_106->setText(QApplication::translate("MainWindow", "106.ubuntu-mozilla-security", 0));
        checkBox_117->setText(QApplication::translate("MainWindow", "117.jdownloader-beta", 0));
        checkBox_118->setText(QApplication::translate("MainWindow", "118.jdownloader-stable", 0));
        checkBox_116->setText(QApplication::translate("MainWindow", "116.compress-uncompress-utils", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_12), QApplication::translate("MainWindow", "Tab 2", 0));
        checkBox_132->setText(QApplication::translate("MainWindow", "132.ukku", 0));
        checkBox_130->setText(QApplication::translate("MainWindow", "130.spaceview", 0));
        checkBox_120->setText(QApplication::translate("MainWindow", "120.samba", 0));
        checkBox_123->setText(QApplication::translate("MainWindow", "123.qpdfview", 0));
        checkBox_122->setText(QApplication::translate("MainWindow", "122.libreoffice", 0));
        checkBox_121->setText(QApplication::translate("MainWindow", "121.evolution", 0));
        checkBox_126->setText(QApplication::translate("MainWindow", "126.uninstallpackages", 0));
        checkBox_125->setText(QApplication::translate("MainWindow", "125.steam", 0));
        checkBox_124->setText(QApplication::translate("MainWindow", "124.thunderbird-nightly", 0));
        checkBox_119->setText(QApplication::translate("MainWindow", "119.peerflix", 0));
        checkBox_133->setText(QApplication::translate("MainWindow", "133.ubunsys", 0));
        checkBox_134->setText(QApplication::translate("MainWindow", "134.android-tools-adb", 0));
        checkBox_135->setText(QApplication::translate("MainWindow", "135.ubuntu-cleaner", 0));
        checkBox_136->setText(QApplication::translate("MainWindow", "136.stacer", 0));
        checkBox_137->setText(QApplication::translate("MainWindow", "137.virtualbox", 0));
        checkBox_138->setText(QApplication::translate("MainWindow", "138.playonlinux", 0));
        checkBox_139->setText(QApplication::translate("MainWindow", "139.kubuntu-ci-unstable", 0));
        checkBox_140->setText(QApplication::translate("MainWindow", "140.qt5ct", 0));
        checkBox_141->setText(QApplication::translate("MainWindow", "141.wakeonlan", 0));
        checkBox_142->setText(QApplication::translate("MainWindow", "142.youtube-dlg", 0));
        checkBox_143->setText(QApplication::translate("MainWindow", "143.chaoticrage", 0));
        checkBox_144->setText(QApplication::translate("MainWindow", "144.keepassxc", 0));
        checkBox_145->setText(QApplication::translate("MainWindow", "145.ucare", 0));
        checkBox_146->setText(QApplication::translate("MainWindow", "146.dekko", 0));
        checkBox_147->setText(QApplication::translate("MainWindow", "147.cerebro", 0));
        checkBox_148->setText(QApplication::translate("MainWindow", "148.rdesktop", 0));
        checkBox_149->setText(QApplication::translate("MainWindow", "149.remmina", 0));
        checkBox_131->setText(QApplication::translate("MainWindow", "131.ungoogled-chromium", 0));
        checkBox_127->setText(QApplication::translate("MainWindow", "127.canonical-livepatch", 0));
        checkBox_128->setText(QApplication::translate("MainWindow", "128.indicator-diskman", 0));
        checkBox_129->setText(QApplication::translate("MainWindow", "129.udisks-indicator", 0));
        checkBox_150->setText(QApplication::translate("MainWindow", "150.spotify", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QApplication::translate("MainWindow", "Tab 3", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Install packages", 0));
        label_66->setText(QApplication::translate("MainWindow", "TO DO: Toggle button", 0));
#ifndef QT_NO_WHATSTHIS
        doInvisibleAsterisksButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        doInvisibleAsterisksButton->setText(QApplication::translate("MainWindow", "Do invisible asterisks\n"
"Set to default", 0));
        doInvisibleAsterisksButton->setShortcut(QString());
        label_67->setText(QApplication::translate("MainWindow", "TO DO: Toggle button", 0));
        label_6->setText(QApplication::translate("MainWindow", "Terminal", 0));
        label_63->setText(QApplication::translate("MainWindow", "Make Password Asterisks Visible\n"
"TO DO: Toggle button", 0));
        label_8->setText(QApplication::translate("MainWindow", "Power", 0));
        label_7->setText(QApplication::translate("MainWindow", "Repositories", 0));
#ifndef QT_NO_WHATSTHIS
        openSourcesListDButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        openSourcesListDButton->setText(QApplication::translate("MainWindow", "Open sources.list.d", 0));
        openSourcesListDButton->setShortcut(QString());
        label_64->setText(QApplication::translate("MainWindow", "Make Password Asterisks Visible\n"
"TO DO: Toggle button", 0));
#ifndef QT_NO_WHATSTHIS
        disableHibernationButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        disableHibernationButton->setText(QApplication::translate("MainWindow", "Disable hibernation", 0));
        disableHibernationButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        doVisibleAsterisksButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        doVisibleAsterisksButton->setText(QApplication::translate("MainWindow", "Do visible asterisks", 0));
        doVisibleAsterisksButton->setShortcut(QString());
        label_65->setText(QApplication::translate("MainWindow", "Open with your default file manager", 0));
#ifndef QT_NO_WHATSTHIS
        enableHibernationButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        enableHibernationButton->setText(QApplication::translate("MainWindow", "Enable hibernation", 0));
        enableHibernationButton->setShortcut(QString());
        label_68->setText(QApplication::translate("MainWindow", "Not recommended\n"
"TO DO: Toggle button\n"
"Only usable if user=usuario", 0));
#ifndef QT_NO_WHATSTHIS
        enableSudoWithoutPassButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        enableSudoWithoutPassButton->setText(QApplication::translate("MainWindow", "Enable sudo without pass", 0));
        enableSudoWithoutPassButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        disableSudoWithoutPassButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        disableSudoWithoutPassButton->setText(QApplication::translate("MainWindow", "Disable sudo without pass", 0));
        disableSudoWithoutPassButton->setShortcut(QString());
        label_10->setText(QApplication::translate("MainWindow", "Security & Passwords", 0));
#ifndef QT_NO_WHATSTHIS
        openSudoersFileButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        openSudoersFileButton->setText(QApplication::translate("MainWindow", "Open sudoers file", 0));
        openSudoersFileButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        backupSudoersFileButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        backupSudoersFileButton->setText(QApplication::translate("MainWindow", "Backup sudoers file", 0));
        backupSudoersFileButton->setShortcut(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_6), QApplication::translate("MainWindow", "Tab 1", 0));
#ifndef QT_NO_WHATSTHIS
        installTemplatesButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        installTemplatesButton->setText(QApplication::translate("MainWindow", "Install Templates", 0));
        installTemplatesButton->setShortcut(QString());
        label_62->setText(QApplication::translate("MainWindow", "This adds content to New Doc Sub-Menu", 0));
        label_5->setText(QApplication::translate("MainWindow", "Documents & Files ", 0));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_7), QApplication::translate("MainWindow", "Tab 2", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Tweaks", 0));
        label_61->setText(QApplication::translate("MainWindow", "do-release-upgrade -d", 0));
#ifndef QT_NO_WHATSTHIS
        upgradeLatestDevButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        upgradeLatestDevButton->setText(QApplication::translate("MainWindow", "Upgrade to latest dev", 0));
        upgradeLatestDevButton->setShortcut(QString());
        toolBox->setItemText(toolBox->indexOf(page_3), QApplication::translate("MainWindow", "Developer", 0));
#ifndef QT_NO_WHATSTHIS
        dist_upgradeButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        dist_upgradeButton->setText(QApplication::translate("MainWindow", "Smart system update", 0));
        dist_upgradeButton->setShortcut(QString());
        label_17->setText(QApplication::translate("MainWindow", "apt-fast -y update &&\n"
"apt-fast -y dist-upgrade", 0));
#ifndef QT_NO_WHATSTHIS
        cleanKernelsButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        cleanKernelsButton->setText(QApplication::translate("MainWindow", "Clean ancient kernels", 0));
        cleanKernelsButton->setShortcut(QString());
        label_59->setText(QApplication::translate("MainWindow", "Recover space from unused kernels", 0));
        label_60->setText(QApplication::translate("MainWindow", "do-release-upgrade", 0));
#ifndef QT_NO_WHATSTHIS
        upgradeLatestStableButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        upgradeLatestStableButton->setText(QApplication::translate("MainWindow", "Upgrade to latest stable", 0));
        upgradeLatestStableButton->setShortcut(QString());
        toolBox->setItemText(toolBox->indexOf(page), QApplication::translate("MainWindow", "Advanced user", 0));
#ifndef QT_NO_WHATSTHIS
        cleanButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        cleanButton->setText(QApplication::translate("MainWindow", "Clean system", 0));
        cleanButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        updateAndUpgradeButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        updateAndUpgradeButton->setText(QApplication::translate("MainWindow", "Default update && upgrade system", 0));
        updateAndUpgradeButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        basicPackagesInstallButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        basicPackagesInstallButton->setText(QApplication::translate("MainWindow", "Exec normal user installation script", 0));
        basicPackagesInstallButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        updateReposButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        updateReposButton->setText(QApplication::translate("MainWindow", "Update repos", 0));
        updateReposButton->setShortcut(QString());
        label_14->setText(QApplication::translate("MainWindow", "apt-fast -y update", 0));
        label_15->setText(QApplication::translate("MainWindow", "apt-fast -y update &&\n"
"apt-fast -y upgrade", 0));
        label_16->setText(QApplication::translate("MainWindow", "apt-get -f install &&\n"
"apt-get -y autoremove &&\n"
"apt-get -y autoclean && \n"
"apt-get -y clean", 0));
        label_31->setText(QApplication::translate("MainWindow", "apt-fast -y upgrade", 0));
#ifndef QT_NO_WHATSTHIS
        upgradeReposButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        upgradeReposButton->setText(QApplication::translate("MainWindow", "Upgrade repos", 0));
        upgradeReposButton->setShortcut(QString());
        label_25->setText(QApplication::translate("MainWindow", "installs latest version of\n"
"installpackages1-minimal of ubuntupackages on git.\n"
"packages for normal users", 0));
        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("MainWindow", "Normal user", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "System", 0));
#ifndef QT_NO_WHATSTHIS
        integrityCheckButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        integrityCheckButton->setText(QString());
        integrityCheckButton->setShortcut(QString());
        label_2->setText(QApplication::translate("MainWindow", "Check system integrity", 0));
        label_3->setText(QApplication::translate("MainWindow", "Fix broken packages (click on each step and check if is solved)", 0));
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_1->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_1->setText(QString());
        fixBrokenPackagesButton_1->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_2->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_2->setText(QString());
        fixBrokenPackagesButton_2->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_3->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_3->setText(QString());
        fixBrokenPackagesButton_3->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_4->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_4->setText(QString());
        fixBrokenPackagesButton_4->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_5->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_5->setText(QString());
        fixBrokenPackagesButton_5->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_6->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_6->setText(QString());
        fixBrokenPackagesButton_6->setShortcut(QString());
        label_18->setText(QApplication::translate("MainWindow", "shutdown -Fr now", 0));
        label_19->setText(QApplication::translate("MainWindow", "apt-fast -y update && apt-fast -y upgrade", 0));
        label_20->setText(QApplication::translate("MainWindow", "apt-get -y --fix-broken install", 0));
        label_21->setText(QApplication::translate("MainWindow", "rm /var/lib/apt/lists/* -vf && apt-get -y update", 0));
        label_22->setText(QApplication::translate("MainWindow", "apt-get -f install && apt-get -y autoremove && apt-get -y autoclean &&\n"
"apt-get -y clean", 0));
        label_23->setText(QApplication::translate("MainWindow", "dpkg --configure -a && apt-get -y update", 0));
        label_24->setText(QApplication::translate("MainWindow", "Open Ubuntu Software Center & click repair if proceed", 0));
        label_9->setText(QApplication::translate("MainWindow", "Repair network", 0));
#ifndef QT_NO_WHATSTHIS
        repairNetworkButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        repairNetworkButton->setText(QString());
        repairNetworkButton->setShortcut(QString());
        label_27->setText(QApplication::translate("MainWindow", "sudo service network-manager restart", 0));
#ifndef QT_NO_WHATSTHIS
        repairGPGKeys->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        repairGPGKeys->setText(QString());
        repairGPGKeys->setShortcut(QString());
        label_28->setText(QApplication::translate("MainWindow", "sudo launchpad-getkeys", 0));
        label_29->setText(QApplication::translate("MainWindow", "Repair missing GPG keys", 0));
        label_30->setText(QApplication::translate("MainWindow", "Be careful, your system will reboot", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Repair", 0));
        menuNuevo->setTitle(QApplication::translate("MainWindow", "File", 0));
        menuEdici_n->setTitle(QApplication::translate("MainWindow", "Edit", 0));
        menuAyuda->setTitle(QApplication::translate("MainWindow", "Help", 0));
        editToolBar->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
