/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionExit;
    QAction *actionPaste;
    QAction *actionAbout;
    QAction *actionAbout_Qt;
    QAction *actionSave_as;
    QAction *actionNew;
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionCopy;
    QAction *actionCut;
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QToolBox *toolBox;
    QWidget *page_3;
    QLabel *label_7;
    QWidget *page;
    QPushButton *dist_upgradeButton;
    QPushButton *upgradeKernelButton;
    QLabel *label_13;
    QLabel *label_17;
    QPushButton *cleanKernelsButton;
    QLabel *label_59;
    QWidget *page_2;
    QPushButton *cleanButton;
    QPushButton *upgradeButton;
    QPushButton *basicPackagesInstallButton;
    QPushButton *updateReposButton;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_31;
    QPushButton *upgradeReposButton;
    QLabel *label_25;
    QWidget *tab_3;
    QLabel *label_5;
    QWidget *tab_2;
    QPushButton *integrityCheckButton;
    QLabel *label_2;
    QLabel *label_3;
    QPushButton *fixBrokenPackagesButton_1;
    QPushButton *fixBrokenPackagesButton_2;
    QPushButton *fixBrokenPackagesButton_3;
    QPushButton *fixBrokenPackagesButton_4;
    QPushButton *fixBrokenPackagesButton_5;
    QPushButton *fixBrokenPackagesButton_6;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_9;
    QPushButton *repairNetworkButton;
    QLabel *label_27;
    QPushButton *repairGPGKeys;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QWidget *tab_4;
    QPushButton *unselectAllButton;
    QPushButton *selectAllButton;
    QPushButton *installSelectedPackagesButton;
    QPushButton *uninstallSelectedPackagesButton_2;
    QPushButton *loadSelectionButton;
    QPushButton *saveSelectionButton;
    QTabWidget *tabWidget_2;
    QWidget *tab_23;
    QCheckBox *checkBox_01;
    QCheckBox *checkBox_02;
    QCheckBox *checkBox_03;
    QWidget *tab_11;
    QCheckBox *checkBox_12;
    QCheckBox *checkBox_13;
    QCheckBox *checkBox_14;
    QCheckBox *checkBox_09;
    QCheckBox *checkBox_11;
    QCheckBox *checkBox_20;
    QCheckBox *checkBox_10;
    QCheckBox *checkBox_21;
    QCheckBox *checkBox_08;
    QCheckBox *checkBox_15;
    QCheckBox *checkBox_05;
    QCheckBox *checkBox_16;
    QCheckBox *checkBox_17;
    QCheckBox *checkBox_18;
    QCheckBox *checkBox_19;
    QCheckBox *checkBox_04;
    QCheckBox *checkBox_06;
    QCheckBox *checkBox_22;
    QCheckBox *checkBox_07;
    QCheckBox *checkBox_23;
    QCheckBox *checkBox_24;
    QCheckBox *checkBox_25;
    QCheckBox *checkBox_26;
    QCheckBox *checkBox_27;
    QCheckBox *checkBox_28;
    QCheckBox *checkBox_29;
    QCheckBox *checkBox_30;
    QCheckBox *checkBox_31;
    QCheckBox *checkBox_32;
    QCheckBox *checkBox_33;
    QCheckBox *checkBox_34;
    QCheckBox *checkBox_35;
    QCheckBox *checkBox_36;
    QCheckBox *checkBox_37;
    QCheckBox *checkBox_38;
    QCheckBox *checkBox_39;
    QCheckBox *checkBox_40;
    QCheckBox *checkBox_46;
    QCheckBox *checkBox_45;
    QCheckBox *checkBox_44;
    QCheckBox *checkBox_43;
    QCheckBox *checkBox_42;
    QCheckBox *checkBox_41;
    QCheckBox *checkBox_47;
    QCheckBox *checkBox_48;
    QCheckBox *checkBox_49;
    QCheckBox *checkBox_50;
    QCheckBox *checkBox_51;
    QCheckBox *checkBox_52;
    QCheckBox *checkBox_53;
    QCheckBox *checkBox_54;
    QCheckBox *checkBox_55;
    QCheckBox *checkBox_56;
    QCheckBox *checkBox_130;
    QCheckBox *checkBox_132;
    QWidget *tab_12;
    QWidget *tab_5;
    QCheckBox *checkBox_57;
    QCheckBox *checkBox_58;
    QWidget *tab_13;
    QCheckBox *checkBox_59;
    QCheckBox *checkBox_60;
    QWidget *tab_6;
    QCheckBox *checkBox_61;
    QWidget *tab_7;
    QWidget *tab_8;
    QCheckBox *checkBox_62;
    QCheckBox *checkBox_63;
    QCheckBox *checkBox_64;
    QCheckBox *checkBox_65;
    QCheckBox *checkBox_66;
    QCheckBox *checkBox_67;
    QCheckBox *checkBox_68;
    QWidget *tab_9;
    QCheckBox *checkBox_69;
    QWidget *tab_10;
    QCheckBox *checkBox_70;
    QCheckBox *checkBox_71;
    QCheckBox *checkBox_72;
    QCheckBox *checkBox_73;
    QWidget *tab_14;
    QCheckBox *checkBox_74;
    QCheckBox *checkBox_75;
    QCheckBox *checkBox_76;
    QWidget *tab_15;
    QCheckBox *checkBox_77;
    QCheckBox *checkBox_78;
    QCheckBox *checkBox_79;
    QCheckBox *checkBox_80;
    QCheckBox *checkBox_81;
    QCheckBox *checkBox_82;
    QCheckBox *checkBox_83;
    QCheckBox *checkBox_84;
    QCheckBox *checkBox_85;
    QCheckBox *checkBox_86;
    QCheckBox *checkBox_87;
    QCheckBox *checkBox_88;
    QCheckBox *checkBox_89;
    QCheckBox *checkBox_90;
    QCheckBox *checkBox_91;
    QCheckBox *checkBox_92;
    QCheckBox *checkBox_93;
    QCheckBox *checkBox_94;
    QWidget *tab_16;
    QCheckBox *checkBox_100;
    QCheckBox *checkBox_101;
    QCheckBox *checkBox_102;
    QCheckBox *checkBox_104;
    QCheckBox *checkBox_105;
    QCheckBox *checkBox_103;
    QCheckBox *checkBox_106;
    QCheckBox *checkBox_107;
    QCheckBox *checkBox_108;
    QCheckBox *checkBox_109;
    QWidget *tab_17;
    QCheckBox *checkBox_110;
    QCheckBox *checkBox_111;
    QCheckBox *checkBox_112;
    QCheckBox *checkBox_113;
    QCheckBox *checkBox_114;
    QCheckBox *checkBox_115;
    QWidget *tab_18;
    QCheckBox *checkBox_116;
    QWidget *tab_19;
    QCheckBox *checkBox_117;
    QCheckBox *checkBox_118;
    QCheckBox *checkBox_119;
    QCheckBox *checkBox_120;
    QWidget *tab_20;
    QWidget *tab_21;
    QCheckBox *checkBox_121;
    QCheckBox *checkBox_122;
    QCheckBox *checkBox_123;
    QCheckBox *checkBox_124;
    QWidget *tab_22;
    QCheckBox *checkBox_125;
    QWidget *tab_24;
    QCheckBox *checkBox_126;
    QMenuBar *menuBar;
    QMenu *menuNuevo;
    QMenu *menuEdici_n;
    QMenu *menuAyuda;
    QToolBar *fileToolBar;
    QStatusBar *statusBar;
    QToolBar *editToolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(669, 549);
        QIcon icon;
        icon.addFile(QStringLiteral(":/images/linux-icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionPaste = new QAction(MainWindow);
        actionPaste->setObjectName(QStringLiteral("actionPaste"));
        actionPaste->setEnabled(true);
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/images/paste.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPaste->setIcon(icon1);
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        actionAbout_Qt = new QAction(MainWindow);
        actionAbout_Qt->setObjectName(QStringLiteral("actionAbout_Qt"));
        actionSave_as = new QAction(MainWindow);
        actionSave_as->setObjectName(QStringLiteral("actionSave_as"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/images/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_as->setIcon(icon2);
        actionNew = new QAction(MainWindow);
        actionNew->setObjectName(QStringLiteral("actionNew"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/images/new.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNew->setIcon(icon3);
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/images/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen->setIcon(icon4);
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        actionSave->setIcon(icon2);
        actionCopy = new QAction(MainWindow);
        actionCopy->setObjectName(QStringLiteral("actionCopy"));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/images/copy.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCopy->setIcon(icon5);
        actionCut = new QAction(MainWindow);
        actionCut->setObjectName(QStringLiteral("actionCut"));
        actionCut->setEnabled(true);
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/images/cut.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCut->setIcon(icon6);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setEnabled(true);
        tabWidget->setGeometry(QRect(9, 10, 651, 451));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        toolBox = new QToolBox(tab);
        toolBox->setObjectName(QStringLiteral("toolBox"));
        toolBox->setEnabled(true);
        toolBox->setGeometry(QRect(10, 10, 631, 371));
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        page_3->setGeometry(QRect(0, 0, 631, 287));
        label_7 = new QLabel(page_3);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 10, 271, 16));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_7->setFont(font);
        toolBox->addItem(page_3, QStringLiteral("Developer"));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        page->setGeometry(QRect(0, 0, 631, 287));
        dist_upgradeButton = new QPushButton(page);
        dist_upgradeButton->setObjectName(QStringLiteral("dist_upgradeButton"));
        dist_upgradeButton->setGeometry(QRect(10, 10, 221, 36));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/images/flecha_arriba.png"), QSize(), QIcon::Normal, QIcon::Off);
        dist_upgradeButton->setIcon(icon7);
        dist_upgradeButton->setIconSize(QSize(30, 30));
        dist_upgradeButton->setCheckable(false);
        upgradeKernelButton = new QPushButton(page);
        upgradeKernelButton->setObjectName(QStringLiteral("upgradeKernelButton"));
        upgradeKernelButton->setGeometry(QRect(10, 60, 221, 36));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/images/kernel.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        upgradeKernelButton->setIcon(icon8);
        upgradeKernelButton->setIconSize(QSize(30, 30));
        upgradeKernelButton->setCheckable(false);
        label_13 = new QLabel(page);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(250, 70, 351, 16));
        QFont font1;
        font1.setBold(false);
        font1.setWeight(50);
        label_13->setFont(font1);
        label_17 = new QLabel(page);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(250, 10, 281, 41));
        label_17->setFont(font1);
        cleanKernelsButton = new QPushButton(page);
        cleanKernelsButton->setObjectName(QStringLiteral("cleanKernelsButton"));
        cleanKernelsButton->setGeometry(QRect(10, 110, 221, 36));
        cleanKernelsButton->setIcon(icon8);
        cleanKernelsButton->setIconSize(QSize(30, 30));
        cleanKernelsButton->setCheckable(false);
        label_59 = new QLabel(page);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(250, 120, 221, 21));
        label_59->setFont(font1);
        toolBox->addItem(page, QStringLiteral("Advanced user"));
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        page_2->setGeometry(QRect(0, 0, 631, 287));
        cleanButton = new QPushButton(page_2);
        cleanButton->setObjectName(QStringLiteral("cleanButton"));
        cleanButton->setGeometry(QRect(10, 210, 271, 36));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/images/escoba.png"), QSize(), QIcon::Normal, QIcon::Off);
        cleanButton->setIcon(icon9);
        cleanButton->setIconSize(QSize(30, 30));
        cleanButton->setCheckable(false);
        upgradeButton = new QPushButton(page_2);
        upgradeButton->setObjectName(QStringLiteral("upgradeButton"));
        upgradeButton->setGeometry(QRect(10, 10, 271, 36));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/images/upgrade.png"), QSize(), QIcon::Normal, QIcon::Off);
        upgradeButton->setIcon(icon10);
        upgradeButton->setIconSize(QSize(30, 30));
        upgradeButton->setCheckable(false);
        basicPackagesInstallButton = new QPushButton(page_2);
        basicPackagesInstallButton->setObjectName(QStringLiteral("basicPackagesInstallButton"));
        basicPackagesInstallButton->setGeometry(QRect(10, 160, 271, 40));
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/images/install.png"), QSize(), QIcon::Normal, QIcon::Off);
        basicPackagesInstallButton->setIcon(icon11);
        basicPackagesInstallButton->setIconSize(QSize(30, 30));
        basicPackagesInstallButton->setCheckable(false);
        updateReposButton = new QPushButton(page_2);
        updateReposButton->setObjectName(QStringLiteral("updateReposButton"));
        updateReposButton->setEnabled(true);
        updateReposButton->setGeometry(QRect(10, 60, 271, 36));
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/images/update.png"), QSize(), QIcon::Normal, QIcon::Off);
        updateReposButton->setIcon(icon12);
        updateReposButton->setIconSize(QSize(30, 30));
        updateReposButton->setCheckable(false);
        label_14 = new QLabel(page_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(290, 70, 251, 16));
        label_14->setFont(font1);
        label_15 = new QLabel(page_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(290, 10, 251, 31));
        label_15->setFont(font1);
        label_16 = new QLabel(page_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(290, 200, 161, 61));
        label_16->setFont(font1);
        label_31 = new QLabel(page_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(290, 120, 251, 16));
        label_31->setFont(font1);
        upgradeReposButton = new QPushButton(page_2);
        upgradeReposButton->setObjectName(QStringLiteral("upgradeReposButton"));
        upgradeReposButton->setEnabled(true);
        upgradeReposButton->setGeometry(QRect(10, 110, 271, 36));
        upgradeReposButton->setIcon(icon12);
        upgradeReposButton->setIconSize(QSize(30, 30));
        upgradeReposButton->setCheckable(false);
        label_25 = new QLabel(page_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(290, 150, 271, 41));
        label_25->setFont(font1);
        toolBox->addItem(page_2, QStringLiteral("Normal user"));
        tabWidget->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        label_5 = new QLabel(tab_3);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 20, 101, 16));
        label_5->setFont(font);
        tabWidget->addTab(tab_3, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        integrityCheckButton = new QPushButton(tab_2);
        integrityCheckButton->setObjectName(QStringLiteral("integrityCheckButton"));
        integrityCheckButton->setGeometry(QRect(10, 40, 40, 36));
        integrityCheckButton->setMaximumSize(QSize(40, 40));
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/images/repair.png"), QSize(), QIcon::Normal, QIcon::Off);
        integrityCheckButton->setIcon(icon13);
        integrityCheckButton->setIconSize(QSize(30, 30));
        integrityCheckButton->setCheckable(false);
        label_2 = new QLabel(tab_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 10, 331, 16));
        label_2->setFont(font);
        label_3 = new QLabel(tab_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 100, 431, 16));
        label_3->setFont(font);
        fixBrokenPackagesButton_1 = new QPushButton(tab_2);
        fixBrokenPackagesButton_1->setObjectName(QStringLiteral("fixBrokenPackagesButton_1"));
        fixBrokenPackagesButton_1->setGeometry(QRect(10, 130, 40, 36));
        fixBrokenPackagesButton_1->setMaximumSize(QSize(40, 40));
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/images/red-number-1.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_1->setIcon(icon14);
        fixBrokenPackagesButton_1->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_1->setCheckable(false);
        fixBrokenPackagesButton_2 = new QPushButton(tab_2);
        fixBrokenPackagesButton_2->setObjectName(QStringLiteral("fixBrokenPackagesButton_2"));
        fixBrokenPackagesButton_2->setGeometry(QRect(10, 170, 40, 36));
        fixBrokenPackagesButton_2->setMaximumSize(QSize(40, 40));
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/images/red-number-2.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_2->setIcon(icon15);
        fixBrokenPackagesButton_2->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_2->setCheckable(false);
        fixBrokenPackagesButton_3 = new QPushButton(tab_2);
        fixBrokenPackagesButton_3->setObjectName(QStringLiteral("fixBrokenPackagesButton_3"));
        fixBrokenPackagesButton_3->setGeometry(QRect(10, 210, 40, 36));
        fixBrokenPackagesButton_3->setMaximumSize(QSize(40, 40));
        QIcon icon16;
        icon16.addFile(QStringLiteral(":/images/red-number-3.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_3->setIcon(icon16);
        fixBrokenPackagesButton_3->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_3->setCheckable(false);
        fixBrokenPackagesButton_4 = new QPushButton(tab_2);
        fixBrokenPackagesButton_4->setObjectName(QStringLiteral("fixBrokenPackagesButton_4"));
        fixBrokenPackagesButton_4->setGeometry(QRect(10, 250, 40, 36));
        fixBrokenPackagesButton_4->setMaximumSize(QSize(40, 40));
        QIcon icon17;
        icon17.addFile(QStringLiteral(":/images/red-number-4.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_4->setIcon(icon17);
        fixBrokenPackagesButton_4->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_4->setCheckable(false);
        fixBrokenPackagesButton_5 = new QPushButton(tab_2);
        fixBrokenPackagesButton_5->setObjectName(QStringLiteral("fixBrokenPackagesButton_5"));
        fixBrokenPackagesButton_5->setGeometry(QRect(10, 290, 40, 36));
        fixBrokenPackagesButton_5->setMaximumSize(QSize(40, 40));
        QIcon icon18;
        icon18.addFile(QStringLiteral(":/images/red-number-5.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_5->setIcon(icon18);
        fixBrokenPackagesButton_5->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_5->setCheckable(false);
        fixBrokenPackagesButton_6 = new QPushButton(tab_2);
        fixBrokenPackagesButton_6->setObjectName(QStringLiteral("fixBrokenPackagesButton_6"));
        fixBrokenPackagesButton_6->setGeometry(QRect(10, 330, 40, 36));
        fixBrokenPackagesButton_6->setMaximumSize(QSize(40, 40));
        QIcon icon19;
        icon19.addFile(QStringLiteral(":/images/red-number-6.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        fixBrokenPackagesButton_6->setIcon(icon19);
        fixBrokenPackagesButton_6->setIconSize(QSize(30, 30));
        fixBrokenPackagesButton_6->setCheckable(false);
        label_18 = new QLabel(tab_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(60, 50, 111, 16));
        label_18->setFont(font1);
        label_19 = new QLabel(tab_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(60, 140, 251, 16));
        label_19->setFont(font1);
        label_20 = new QLabel(tab_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(60, 180, 251, 16));
        label_20->setFont(font1);
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(60, 220, 281, 16));
        label_21->setFont(font1);
        label_22 = new QLabel(tab_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(60, 250, 491, 31));
        label_22->setFont(font1);
        label_23 = new QLabel(tab_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(60, 300, 251, 16));
        label_23->setFont(font1);
        label_24 = new QLabel(tab_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(60, 340, 331, 16));
        label_24->setFont(font1);
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(350, 10, 111, 16));
        label_9->setFont(font);
        repairNetworkButton = new QPushButton(tab_2);
        repairNetworkButton->setObjectName(QStringLiteral("repairNetworkButton"));
        repairNetworkButton->setGeometry(QRect(350, 40, 40, 36));
        repairNetworkButton->setMaximumSize(QSize(40, 40));
        repairNetworkButton->setIcon(icon13);
        repairNetworkButton->setIconSize(QSize(30, 30));
        repairNetworkButton->setCheckable(false);
        label_27 = new QLabel(tab_2);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(400, 50, 231, 16));
        label_27->setFont(font1);
        repairGPGKeys = new QPushButton(tab_2);
        repairGPGKeys->setObjectName(QStringLiteral("repairGPGKeys"));
        repairGPGKeys->setGeometry(QRect(350, 170, 40, 36));
        repairGPGKeys->setMaximumSize(QSize(40, 40));
        repairGPGKeys->setIcon(icon13);
        repairGPGKeys->setIconSize(QSize(30, 30));
        repairGPGKeys->setCheckable(false);
        label_28 = new QLabel(tab_2);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(400, 180, 151, 16));
        label_28->setFont(font1);
        label_29 = new QLabel(tab_2);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(350, 140, 171, 16));
        label_29->setFont(font);
        label_30 = new QLabel(tab_2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(60, 30, 241, 16));
        label_30->setFont(font);
        tabWidget->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        unselectAllButton = new QPushButton(tab_4);
        unselectAllButton->setObjectName(QStringLiteral("unselectAllButton"));
        unselectAllButton->setGeometry(QRect(550, 30, 81, 23));
        selectAllButton = new QPushButton(tab_4);
        selectAllButton->setObjectName(QStringLiteral("selectAllButton"));
        selectAllButton->setGeometry(QRect(550, 60, 81, 23));
        installSelectedPackagesButton = new QPushButton(tab_4);
        installSelectedPackagesButton->setObjectName(QStringLiteral("installSelectedPackagesButton"));
        installSelectedPackagesButton->setGeometry(QRect(550, 120, 81, 23));
        uninstallSelectedPackagesButton_2 = new QPushButton(tab_4);
        uninstallSelectedPackagesButton_2->setObjectName(QStringLiteral("uninstallSelectedPackagesButton_2"));
        uninstallSelectedPackagesButton_2->setEnabled(false);
        uninstallSelectedPackagesButton_2->setGeometry(QRect(550, 150, 81, 23));
        uninstallSelectedPackagesButton_2->setCheckable(false);
        loadSelectionButton = new QPushButton(tab_4);
        loadSelectionButton->setObjectName(QStringLiteral("loadSelectionButton"));
        loadSelectionButton->setGeometry(QRect(550, 210, 81, 23));
        saveSelectionButton = new QPushButton(tab_4);
        saveSelectionButton->setObjectName(QStringLiteral("saveSelectionButton"));
        saveSelectionButton->setEnabled(false);
        saveSelectionButton->setGeometry(QRect(550, 240, 81, 23));
        tabWidget_2 = new QTabWidget(tab_4);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(0, 0, 541, 411));
        tab_23 = new QWidget();
        tab_23->setObjectName(QStringLiteral("tab_23"));
        checkBox_01 = new QCheckBox(tab_23);
        checkBox_01->setObjectName(QStringLiteral("checkBox_01"));
        checkBox_01->setGeometry(QRect(20, 0, 141, 23));
        checkBox_02 = new QCheckBox(tab_23);
        checkBox_02->setObjectName(QStringLiteral("checkBox_02"));
        checkBox_02->setGeometry(QRect(20, 20, 141, 23));
        checkBox_03 = new QCheckBox(tab_23);
        checkBox_03->setObjectName(QStringLiteral("checkBox_03"));
        checkBox_03->setGeometry(QRect(20, 40, 141, 23));
        tabWidget_2->addTab(tab_23, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QStringLiteral("tab_11"));
        checkBox_12 = new QCheckBox(tab_11);
        checkBox_12->setObjectName(QStringLiteral("checkBox_12"));
        checkBox_12->setGeometry(QRect(20, 160, 101, 23));
        checkBox_13 = new QCheckBox(tab_11);
        checkBox_13->setObjectName(QStringLiteral("checkBox_13"));
        checkBox_13->setGeometry(QRect(20, 180, 201, 23));
        checkBox_14 = new QCheckBox(tab_11);
        checkBox_14->setObjectName(QStringLiteral("checkBox_14"));
        checkBox_14->setGeometry(QRect(20, 200, 191, 23));
        checkBox_09 = new QCheckBox(tab_11);
        checkBox_09->setObjectName(QStringLiteral("checkBox_09"));
        checkBox_09->setGeometry(QRect(20, 100, 141, 23));
        checkBox_11 = new QCheckBox(tab_11);
        checkBox_11->setObjectName(QStringLiteral("checkBox_11"));
        checkBox_11->setGeometry(QRect(20, 140, 181, 23));
        checkBox_20 = new QCheckBox(tab_11);
        checkBox_20->setObjectName(QStringLiteral("checkBox_20"));
        checkBox_20->setGeometry(QRect(20, 320, 191, 23));
        checkBox_10 = new QCheckBox(tab_11);
        checkBox_10->setObjectName(QStringLiteral("checkBox_10"));
        checkBox_10->setGeometry(QRect(20, 120, 141, 23));
        checkBox_21 = new QCheckBox(tab_11);
        checkBox_21->setObjectName(QStringLiteral("checkBox_21"));
        checkBox_21->setGeometry(QRect(20, 340, 191, 23));
        checkBox_08 = new QCheckBox(tab_11);
        checkBox_08->setObjectName(QStringLiteral("checkBox_08"));
        checkBox_08->setGeometry(QRect(20, 80, 141, 23));
        checkBox_15 = new QCheckBox(tab_11);
        checkBox_15->setObjectName(QStringLiteral("checkBox_15"));
        checkBox_15->setGeometry(QRect(20, 220, 191, 23));
        checkBox_05 = new QCheckBox(tab_11);
        checkBox_05->setObjectName(QStringLiteral("checkBox_05"));
        checkBox_05->setGeometry(QRect(20, 20, 141, 23));
        checkBox_16 = new QCheckBox(tab_11);
        checkBox_16->setObjectName(QStringLiteral("checkBox_16"));
        checkBox_16->setGeometry(QRect(20, 240, 191, 23));
        checkBox_17 = new QCheckBox(tab_11);
        checkBox_17->setObjectName(QStringLiteral("checkBox_17"));
        checkBox_17->setGeometry(QRect(20, 260, 191, 23));
        checkBox_18 = new QCheckBox(tab_11);
        checkBox_18->setObjectName(QStringLiteral("checkBox_18"));
        checkBox_18->setGeometry(QRect(20, 280, 191, 23));
        checkBox_19 = new QCheckBox(tab_11);
        checkBox_19->setObjectName(QStringLiteral("checkBox_19"));
        checkBox_19->setGeometry(QRect(20, 300, 191, 23));
        checkBox_04 = new QCheckBox(tab_11);
        checkBox_04->setObjectName(QStringLiteral("checkBox_04"));
        checkBox_04->setGeometry(QRect(20, 0, 141, 23));
        checkBox_06 = new QCheckBox(tab_11);
        checkBox_06->setObjectName(QStringLiteral("checkBox_06"));
        checkBox_06->setGeometry(QRect(20, 40, 141, 23));
        checkBox_22 = new QCheckBox(tab_11);
        checkBox_22->setObjectName(QStringLiteral("checkBox_22"));
        checkBox_22->setGeometry(QRect(20, 360, 111, 23));
        checkBox_07 = new QCheckBox(tab_11);
        checkBox_07->setObjectName(QStringLiteral("checkBox_07"));
        checkBox_07->setGeometry(QRect(20, 60, 141, 23));
        checkBox_23 = new QCheckBox(tab_11);
        checkBox_23->setObjectName(QStringLiteral("checkBox_23"));
        checkBox_23->setGeometry(QRect(230, 0, 111, 23));
        checkBox_24 = new QCheckBox(tab_11);
        checkBox_24->setObjectName(QStringLiteral("checkBox_24"));
        checkBox_24->setGeometry(QRect(230, 20, 111, 23));
        checkBox_25 = new QCheckBox(tab_11);
        checkBox_25->setObjectName(QStringLiteral("checkBox_25"));
        checkBox_25->setGeometry(QRect(230, 40, 111, 23));
        checkBox_26 = new QCheckBox(tab_11);
        checkBox_26->setObjectName(QStringLiteral("checkBox_26"));
        checkBox_26->setGeometry(QRect(230, 60, 111, 23));
        checkBox_27 = new QCheckBox(tab_11);
        checkBox_27->setObjectName(QStringLiteral("checkBox_27"));
        checkBox_27->setGeometry(QRect(230, 80, 111, 23));
        checkBox_28 = new QCheckBox(tab_11);
        checkBox_28->setObjectName(QStringLiteral("checkBox_28"));
        checkBox_28->setGeometry(QRect(230, 100, 111, 23));
        checkBox_29 = new QCheckBox(tab_11);
        checkBox_29->setObjectName(QStringLiteral("checkBox_29"));
        checkBox_29->setGeometry(QRect(230, 120, 131, 23));
        checkBox_30 = new QCheckBox(tab_11);
        checkBox_30->setObjectName(QStringLiteral("checkBox_30"));
        checkBox_30->setGeometry(QRect(230, 140, 141, 23));
        checkBox_31 = new QCheckBox(tab_11);
        checkBox_31->setObjectName(QStringLiteral("checkBox_31"));
        checkBox_31->setGeometry(QRect(230, 160, 141, 23));
        checkBox_32 = new QCheckBox(tab_11);
        checkBox_32->setObjectName(QStringLiteral("checkBox_32"));
        checkBox_32->setGeometry(QRect(230, 180, 111, 23));
        checkBox_33 = new QCheckBox(tab_11);
        checkBox_33->setObjectName(QStringLiteral("checkBox_33"));
        checkBox_33->setGeometry(QRect(230, 200, 111, 23));
        checkBox_34 = new QCheckBox(tab_11);
        checkBox_34->setObjectName(QStringLiteral("checkBox_34"));
        checkBox_34->setGeometry(QRect(230, 220, 111, 23));
        checkBox_35 = new QCheckBox(tab_11);
        checkBox_35->setObjectName(QStringLiteral("checkBox_35"));
        checkBox_35->setGeometry(QRect(230, 240, 151, 23));
        checkBox_36 = new QCheckBox(tab_11);
        checkBox_36->setObjectName(QStringLiteral("checkBox_36"));
        checkBox_36->setGeometry(QRect(230, 260, 111, 23));
        checkBox_37 = new QCheckBox(tab_11);
        checkBox_37->setObjectName(QStringLiteral("checkBox_37"));
        checkBox_37->setGeometry(QRect(230, 280, 111, 23));
        checkBox_38 = new QCheckBox(tab_11);
        checkBox_38->setObjectName(QStringLiteral("checkBox_38"));
        checkBox_38->setGeometry(QRect(230, 300, 161, 23));
        checkBox_39 = new QCheckBox(tab_11);
        checkBox_39->setObjectName(QStringLiteral("checkBox_39"));
        checkBox_39->setGeometry(QRect(230, 320, 111, 23));
        checkBox_40 = new QCheckBox(tab_11);
        checkBox_40->setObjectName(QStringLiteral("checkBox_40"));
        checkBox_40->setGeometry(QRect(230, 340, 121, 23));
        checkBox_46 = new QCheckBox(tab_11);
        checkBox_46->setObjectName(QStringLiteral("checkBox_46"));
        checkBox_46->setGeometry(QRect(390, 80, 111, 23));
        checkBox_45 = new QCheckBox(tab_11);
        checkBox_45->setObjectName(QStringLiteral("checkBox_45"));
        checkBox_45->setGeometry(QRect(390, 60, 111, 23));
        checkBox_44 = new QCheckBox(tab_11);
        checkBox_44->setObjectName(QStringLiteral("checkBox_44"));
        checkBox_44->setGeometry(QRect(390, 40, 141, 23));
        checkBox_43 = new QCheckBox(tab_11);
        checkBox_43->setObjectName(QStringLiteral("checkBox_43"));
        checkBox_43->setGeometry(QRect(390, 20, 111, 23));
        checkBox_42 = new QCheckBox(tab_11);
        checkBox_42->setObjectName(QStringLiteral("checkBox_42"));
        checkBox_42->setGeometry(QRect(390, 0, 111, 23));
        checkBox_41 = new QCheckBox(tab_11);
        checkBox_41->setObjectName(QStringLiteral("checkBox_41"));
        checkBox_41->setGeometry(QRect(230, 360, 111, 23));
        checkBox_47 = new QCheckBox(tab_11);
        checkBox_47->setObjectName(QStringLiteral("checkBox_47"));
        checkBox_47->setGeometry(QRect(390, 100, 111, 23));
        checkBox_48 = new QCheckBox(tab_11);
        checkBox_48->setObjectName(QStringLiteral("checkBox_48"));
        checkBox_48->setGeometry(QRect(390, 120, 111, 23));
        checkBox_49 = new QCheckBox(tab_11);
        checkBox_49->setObjectName(QStringLiteral("checkBox_49"));
        checkBox_49->setGeometry(QRect(390, 140, 121, 23));
        checkBox_50 = new QCheckBox(tab_11);
        checkBox_50->setObjectName(QStringLiteral("checkBox_50"));
        checkBox_50->setGeometry(QRect(390, 160, 111, 23));
        checkBox_51 = new QCheckBox(tab_11);
        checkBox_51->setObjectName(QStringLiteral("checkBox_51"));
        checkBox_51->setGeometry(QRect(390, 180, 131, 23));
        checkBox_52 = new QCheckBox(tab_11);
        checkBox_52->setObjectName(QStringLiteral("checkBox_52"));
        checkBox_52->setGeometry(QRect(390, 200, 121, 23));
        checkBox_53 = new QCheckBox(tab_11);
        checkBox_53->setObjectName(QStringLiteral("checkBox_53"));
        checkBox_53->setGeometry(QRect(390, 220, 111, 23));
        checkBox_54 = new QCheckBox(tab_11);
        checkBox_54->setObjectName(QStringLiteral("checkBox_54"));
        checkBox_54->setGeometry(QRect(390, 240, 121, 23));
        checkBox_55 = new QCheckBox(tab_11);
        checkBox_55->setObjectName(QStringLiteral("checkBox_55"));
        checkBox_55->setGeometry(QRect(390, 260, 161, 23));
        checkBox_56 = new QCheckBox(tab_11);
        checkBox_56->setObjectName(QStringLiteral("checkBox_56"));
        checkBox_56->setGeometry(QRect(390, 280, 161, 23));
        checkBox_130 = new QCheckBox(tab_11);
        checkBox_130->setObjectName(QStringLiteral("checkBox_130"));
        checkBox_130->setGeometry(QRect(390, 300, 161, 23));
        checkBox_132 = new QCheckBox(tab_11);
        checkBox_132->setObjectName(QStringLiteral("checkBox_132"));
        checkBox_132->setGeometry(QRect(390, 320, 161, 23));
        tabWidget_2->addTab(tab_11, QString());
        tab_12 = new QWidget();
        tab_12->setObjectName(QStringLiteral("tab_12"));
        tabWidget_2->addTab(tab_12, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        checkBox_57 = new QCheckBox(tab_5);
        checkBox_57->setObjectName(QStringLiteral("checkBox_57"));
        checkBox_57->setGeometry(QRect(20, 0, 191, 23));
        checkBox_58 = new QCheckBox(tab_5);
        checkBox_58->setObjectName(QStringLiteral("checkBox_58"));
        checkBox_58->setGeometry(QRect(20, 20, 191, 23));
        tabWidget_2->addTab(tab_5, QString());
        tab_13 = new QWidget();
        tab_13->setObjectName(QStringLiteral("tab_13"));
        checkBox_59 = new QCheckBox(tab_13);
        checkBox_59->setObjectName(QStringLiteral("checkBox_59"));
        checkBox_59->setGeometry(QRect(20, 0, 191, 23));
        checkBox_60 = new QCheckBox(tab_13);
        checkBox_60->setObjectName(QStringLiteral("checkBox_60"));
        checkBox_60->setGeometry(QRect(20, 20, 191, 23));
        tabWidget_2->addTab(tab_13, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        checkBox_61 = new QCheckBox(tab_6);
        checkBox_61->setObjectName(QStringLiteral("checkBox_61"));
        checkBox_61->setGeometry(QRect(20, 0, 191, 23));
        tabWidget_2->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        tabWidget_2->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        checkBox_62 = new QCheckBox(tab_8);
        checkBox_62->setObjectName(QStringLiteral("checkBox_62"));
        checkBox_62->setGeometry(QRect(20, 0, 191, 23));
        checkBox_63 = new QCheckBox(tab_8);
        checkBox_63->setObjectName(QStringLiteral("checkBox_63"));
        checkBox_63->setGeometry(QRect(20, 20, 191, 23));
        checkBox_64 = new QCheckBox(tab_8);
        checkBox_64->setObjectName(QStringLiteral("checkBox_64"));
        checkBox_64->setGeometry(QRect(20, 40, 191, 23));
        checkBox_65 = new QCheckBox(tab_8);
        checkBox_65->setObjectName(QStringLiteral("checkBox_65"));
        checkBox_65->setGeometry(QRect(20, 60, 191, 23));
        checkBox_66 = new QCheckBox(tab_8);
        checkBox_66->setObjectName(QStringLiteral("checkBox_66"));
        checkBox_66->setGeometry(QRect(20, 80, 191, 23));
        checkBox_67 = new QCheckBox(tab_8);
        checkBox_67->setObjectName(QStringLiteral("checkBox_67"));
        checkBox_67->setGeometry(QRect(20, 100, 191, 23));
        checkBox_68 = new QCheckBox(tab_8);
        checkBox_68->setObjectName(QStringLiteral("checkBox_68"));
        checkBox_68->setGeometry(QRect(20, 120, 191, 23));
        tabWidget_2->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        checkBox_69 = new QCheckBox(tab_9);
        checkBox_69->setObjectName(QStringLiteral("checkBox_69"));
        checkBox_69->setGeometry(QRect(20, 0, 191, 23));
        tabWidget_2->addTab(tab_9, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        checkBox_70 = new QCheckBox(tab_10);
        checkBox_70->setObjectName(QStringLiteral("checkBox_70"));
        checkBox_70->setGeometry(QRect(20, 0, 191, 23));
        checkBox_71 = new QCheckBox(tab_10);
        checkBox_71->setObjectName(QStringLiteral("checkBox_71"));
        checkBox_71->setGeometry(QRect(20, 20, 191, 23));
        checkBox_72 = new QCheckBox(tab_10);
        checkBox_72->setObjectName(QStringLiteral("checkBox_72"));
        checkBox_72->setGeometry(QRect(20, 40, 191, 23));
        checkBox_73 = new QCheckBox(tab_10);
        checkBox_73->setObjectName(QStringLiteral("checkBox_73"));
        checkBox_73->setGeometry(QRect(20, 60, 191, 23));
        tabWidget_2->addTab(tab_10, QString());
        tab_14 = new QWidget();
        tab_14->setObjectName(QStringLiteral("tab_14"));
        checkBox_74 = new QCheckBox(tab_14);
        checkBox_74->setObjectName(QStringLiteral("checkBox_74"));
        checkBox_74->setGeometry(QRect(20, 0, 191, 23));
        checkBox_75 = new QCheckBox(tab_14);
        checkBox_75->setObjectName(QStringLiteral("checkBox_75"));
        checkBox_75->setGeometry(QRect(20, 20, 191, 23));
        checkBox_76 = new QCheckBox(tab_14);
        checkBox_76->setObjectName(QStringLiteral("checkBox_76"));
        checkBox_76->setGeometry(QRect(20, 40, 191, 23));
        tabWidget_2->addTab(tab_14, QString());
        tab_15 = new QWidget();
        tab_15->setObjectName(QStringLiteral("tab_15"));
        checkBox_77 = new QCheckBox(tab_15);
        checkBox_77->setObjectName(QStringLiteral("checkBox_77"));
        checkBox_77->setGeometry(QRect(20, 0, 191, 23));
        checkBox_78 = new QCheckBox(tab_15);
        checkBox_78->setObjectName(QStringLiteral("checkBox_78"));
        checkBox_78->setGeometry(QRect(20, 20, 191, 23));
        checkBox_79 = new QCheckBox(tab_15);
        checkBox_79->setObjectName(QStringLiteral("checkBox_79"));
        checkBox_79->setGeometry(QRect(20, 40, 191, 23));
        checkBox_80 = new QCheckBox(tab_15);
        checkBox_80->setObjectName(QStringLiteral("checkBox_80"));
        checkBox_80->setGeometry(QRect(20, 60, 191, 23));
        checkBox_81 = new QCheckBox(tab_15);
        checkBox_81->setObjectName(QStringLiteral("checkBox_81"));
        checkBox_81->setGeometry(QRect(20, 80, 191, 23));
        checkBox_82 = new QCheckBox(tab_15);
        checkBox_82->setObjectName(QStringLiteral("checkBox_82"));
        checkBox_82->setGeometry(QRect(20, 100, 191, 23));
        checkBox_83 = new QCheckBox(tab_15);
        checkBox_83->setObjectName(QStringLiteral("checkBox_83"));
        checkBox_83->setGeometry(QRect(20, 120, 191, 23));
        checkBox_84 = new QCheckBox(tab_15);
        checkBox_84->setObjectName(QStringLiteral("checkBox_84"));
        checkBox_84->setGeometry(QRect(20, 140, 191, 23));
        checkBox_85 = new QCheckBox(tab_15);
        checkBox_85->setObjectName(QStringLiteral("checkBox_85"));
        checkBox_85->setGeometry(QRect(20, 160, 191, 23));
        checkBox_86 = new QCheckBox(tab_15);
        checkBox_86->setObjectName(QStringLiteral("checkBox_86"));
        checkBox_86->setGeometry(QRect(20, 180, 191, 23));
        checkBox_87 = new QCheckBox(tab_15);
        checkBox_87->setObjectName(QStringLiteral("checkBox_87"));
        checkBox_87->setGeometry(QRect(20, 200, 191, 23));
        checkBox_88 = new QCheckBox(tab_15);
        checkBox_88->setObjectName(QStringLiteral("checkBox_88"));
        checkBox_88->setGeometry(QRect(20, 220, 191, 23));
        checkBox_89 = new QCheckBox(tab_15);
        checkBox_89->setObjectName(QStringLiteral("checkBox_89"));
        checkBox_89->setGeometry(QRect(20, 240, 191, 23));
        checkBox_90 = new QCheckBox(tab_15);
        checkBox_90->setObjectName(QStringLiteral("checkBox_90"));
        checkBox_90->setGeometry(QRect(20, 260, 191, 23));
        checkBox_91 = new QCheckBox(tab_15);
        checkBox_91->setObjectName(QStringLiteral("checkBox_91"));
        checkBox_91->setGeometry(QRect(20, 280, 191, 23));
        checkBox_92 = new QCheckBox(tab_15);
        checkBox_92->setObjectName(QStringLiteral("checkBox_92"));
        checkBox_92->setGeometry(QRect(20, 300, 191, 23));
        checkBox_93 = new QCheckBox(tab_15);
        checkBox_93->setObjectName(QStringLiteral("checkBox_93"));
        checkBox_93->setGeometry(QRect(20, 320, 191, 23));
        checkBox_94 = new QCheckBox(tab_15);
        checkBox_94->setObjectName(QStringLiteral("checkBox_94"));
        checkBox_94->setGeometry(QRect(200, 0, 191, 23));
        tabWidget_2->addTab(tab_15, QString());
        tab_16 = new QWidget();
        tab_16->setObjectName(QStringLiteral("tab_16"));
        checkBox_100 = new QCheckBox(tab_16);
        checkBox_100->setObjectName(QStringLiteral("checkBox_100"));
        checkBox_100->setGeometry(QRect(20, 0, 191, 23));
        checkBox_101 = new QCheckBox(tab_16);
        checkBox_101->setObjectName(QStringLiteral("checkBox_101"));
        checkBox_101->setGeometry(QRect(20, 20, 191, 23));
        checkBox_102 = new QCheckBox(tab_16);
        checkBox_102->setObjectName(QStringLiteral("checkBox_102"));
        checkBox_102->setGeometry(QRect(20, 40, 191, 23));
        checkBox_104 = new QCheckBox(tab_16);
        checkBox_104->setObjectName(QStringLiteral("checkBox_104"));
        checkBox_104->setGeometry(QRect(20, 80, 211, 23));
        checkBox_105 = new QCheckBox(tab_16);
        checkBox_105->setObjectName(QStringLiteral("checkBox_105"));
        checkBox_105->setGeometry(QRect(20, 100, 211, 23));
        checkBox_103 = new QCheckBox(tab_16);
        checkBox_103->setObjectName(QStringLiteral("checkBox_103"));
        checkBox_103->setGeometry(QRect(20, 60, 191, 23));
        checkBox_106 = new QCheckBox(tab_16);
        checkBox_106->setObjectName(QStringLiteral("checkBox_106"));
        checkBox_106->setGeometry(QRect(20, 120, 211, 23));
        checkBox_107 = new QCheckBox(tab_16);
        checkBox_107->setObjectName(QStringLiteral("checkBox_107"));
        checkBox_107->setGeometry(QRect(20, 140, 211, 23));
        checkBox_108 = new QCheckBox(tab_16);
        checkBox_108->setObjectName(QStringLiteral("checkBox_108"));
        checkBox_108->setGeometry(QRect(20, 160, 211, 23));
        checkBox_109 = new QCheckBox(tab_16);
        checkBox_109->setObjectName(QStringLiteral("checkBox_109"));
        checkBox_109->setGeometry(QRect(20, 180, 211, 23));
        tabWidget_2->addTab(tab_16, QString());
        tab_17 = new QWidget();
        tab_17->setObjectName(QStringLiteral("tab_17"));
        checkBox_110 = new QCheckBox(tab_17);
        checkBox_110->setObjectName(QStringLiteral("checkBox_110"));
        checkBox_110->setGeometry(QRect(20, 0, 211, 23));
        checkBox_111 = new QCheckBox(tab_17);
        checkBox_111->setObjectName(QStringLiteral("checkBox_111"));
        checkBox_111->setGeometry(QRect(20, 20, 211, 23));
        checkBox_112 = new QCheckBox(tab_17);
        checkBox_112->setObjectName(QStringLiteral("checkBox_112"));
        checkBox_112->setGeometry(QRect(20, 40, 211, 23));
        checkBox_113 = new QCheckBox(tab_17);
        checkBox_113->setObjectName(QStringLiteral("checkBox_113"));
        checkBox_113->setGeometry(QRect(20, 60, 211, 23));
        checkBox_114 = new QCheckBox(tab_17);
        checkBox_114->setObjectName(QStringLiteral("checkBox_114"));
        checkBox_114->setGeometry(QRect(20, 80, 211, 23));
        checkBox_115 = new QCheckBox(tab_17);
        checkBox_115->setObjectName(QStringLiteral("checkBox_115"));
        checkBox_115->setGeometry(QRect(20, 100, 211, 23));
        tabWidget_2->addTab(tab_17, QString());
        tab_18 = new QWidget();
        tab_18->setObjectName(QStringLiteral("tab_18"));
        checkBox_116 = new QCheckBox(tab_18);
        checkBox_116->setObjectName(QStringLiteral("checkBox_116"));
        checkBox_116->setGeometry(QRect(20, 0, 211, 23));
        tabWidget_2->addTab(tab_18, QString());
        tab_19 = new QWidget();
        tab_19->setObjectName(QStringLiteral("tab_19"));
        checkBox_117 = new QCheckBox(tab_19);
        checkBox_117->setObjectName(QStringLiteral("checkBox_117"));
        checkBox_117->setGeometry(QRect(20, 0, 211, 23));
        checkBox_118 = new QCheckBox(tab_19);
        checkBox_118->setObjectName(QStringLiteral("checkBox_118"));
        checkBox_118->setGeometry(QRect(20, 20, 211, 23));
        checkBox_119 = new QCheckBox(tab_19);
        checkBox_119->setObjectName(QStringLiteral("checkBox_119"));
        checkBox_119->setGeometry(QRect(20, 40, 211, 23));
        checkBox_120 = new QCheckBox(tab_19);
        checkBox_120->setObjectName(QStringLiteral("checkBox_120"));
        checkBox_120->setGeometry(QRect(20, 60, 211, 23));
        tabWidget_2->addTab(tab_19, QString());
        tab_20 = new QWidget();
        tab_20->setObjectName(QStringLiteral("tab_20"));
        tabWidget_2->addTab(tab_20, QString());
        tab_21 = new QWidget();
        tab_21->setObjectName(QStringLiteral("tab_21"));
        checkBox_121 = new QCheckBox(tab_21);
        checkBox_121->setObjectName(QStringLiteral("checkBox_121"));
        checkBox_121->setGeometry(QRect(20, 0, 191, 23));
        checkBox_122 = new QCheckBox(tab_21);
        checkBox_122->setObjectName(QStringLiteral("checkBox_122"));
        checkBox_122->setGeometry(QRect(20, 20, 191, 23));
        checkBox_123 = new QCheckBox(tab_21);
        checkBox_123->setObjectName(QStringLiteral("checkBox_123"));
        checkBox_123->setGeometry(QRect(20, 40, 191, 23));
        checkBox_124 = new QCheckBox(tab_21);
        checkBox_124->setObjectName(QStringLiteral("checkBox_124"));
        checkBox_124->setGeometry(QRect(20, 60, 191, 23));
        tabWidget_2->addTab(tab_21, QString());
        tab_22 = new QWidget();
        tab_22->setObjectName(QStringLiteral("tab_22"));
        checkBox_125 = new QCheckBox(tab_22);
        checkBox_125->setObjectName(QStringLiteral("checkBox_125"));
        checkBox_125->setGeometry(QRect(20, 0, 191, 23));
        tabWidget_2->addTab(tab_22, QString());
        tab_24 = new QWidget();
        tab_24->setObjectName(QStringLiteral("tab_24"));
        checkBox_126 = new QCheckBox(tab_24);
        checkBox_126->setObjectName(QStringLiteral("checkBox_126"));
        checkBox_126->setGeometry(QRect(20, 0, 191, 23));
        tabWidget_2->addTab(tab_24, QString());
        tabWidget->addTab(tab_4, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 669, 19));
        menuNuevo = new QMenu(menuBar);
        menuNuevo->setObjectName(QStringLiteral("menuNuevo"));
        menuEdici_n = new QMenu(menuBar);
        menuEdici_n->setObjectName(QStringLiteral("menuEdici_n"));
        menuAyuda = new QMenu(menuBar);
        menuAyuda->setObjectName(QStringLiteral("menuAyuda"));
        MainWindow->setMenuBar(menuBar);
        fileToolBar = new QToolBar(MainWindow);
        fileToolBar->setObjectName(QStringLiteral("fileToolBar"));
        fileToolBar->setEnabled(false);
        fileToolBar->setMovable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, fileToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        editToolBar = new QToolBar(MainWindow);
        editToolBar->setObjectName(QStringLiteral("editToolBar"));
        editToolBar->setEnabled(false);
        editToolBar->setMovable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, editToolBar);

        menuBar->addAction(menuNuevo->menuAction());
        menuBar->addAction(menuEdici_n->menuAction());
        menuBar->addAction(menuAyuda->menuAction());
        menuNuevo->addSeparator();
        menuNuevo->addAction(actionNew);
        menuNuevo->addAction(actionOpen);
        menuNuevo->addAction(actionSave);
        menuNuevo->addAction(actionSave_as);
        menuNuevo->addSeparator();
        menuNuevo->addAction(actionExit);
        menuEdici_n->addAction(actionCopy);
        menuEdici_n->addAction(actionCut);
        menuEdici_n->addAction(actionPaste);
        menuAyuda->addAction(actionAbout);
        menuAyuda->addAction(actionAbout_Qt);
        fileToolBar->addAction(actionNew);
        fileToolBar->addAction(actionSave);
        editToolBar->addAction(actionCut);
        editToolBar->addAction(actionCopy);
        editToolBar->addAction(actionPaste);

        retranslateUi(MainWindow);
        QObject::connect(actionExit, SIGNAL(triggered()), MainWindow, SLOT(close()));

        tabWidget->setCurrentIndex(0);
        toolBox->setCurrentIndex(2);
        tabWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "ubunsys", 0));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0));
        actionPaste->setText(QApplication::translate("MainWindow", "Paste", 0));
        actionAbout->setText(QApplication::translate("MainWindow", "About", 0));
        actionAbout_Qt->setText(QApplication::translate("MainWindow", "About Qt", 0));
        actionSave_as->setText(QApplication::translate("MainWindow", "Save as...", 0));
        actionNew->setText(QApplication::translate("MainWindow", "New", 0));
        actionOpen->setText(QApplication::translate("MainWindow", "Open", 0));
        actionSave->setText(QApplication::translate("MainWindow", "Save", 0));
        actionCopy->setText(QApplication::translate("MainWindow", "Copy", 0));
        actionCut->setText(QApplication::translate("MainWindow", "Cut", 0));
        actionCut->setIconText(QApplication::translate("MainWindow", "Cortar", 0));
        label_7->setText(QApplication::translate("MainWindow", "Coming soon...", 0));
        toolBox->setItemText(toolBox->indexOf(page_3), QApplication::translate("MainWindow", "Developer", 0));
#ifndef QT_NO_WHATSTHIS
        dist_upgradeButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        dist_upgradeButton->setText(QApplication::translate("MainWindow", "Smart system update", 0));
        dist_upgradeButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        upgradeKernelButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        upgradeKernelButton->setText(QApplication::translate("MainWindow", "Exec mainline kernel update", 0));
        upgradeKernelButton->setShortcut(QString());
        label_13->setText(QApplication::translate("MainWindow", "Base from: https://github.com/medigeek/kmp-downloader", 0));
        label_17->setText(QApplication::translate("MainWindow", "apt-get -y update &&\n"
"apt-get -y dist-upgrade", 0));
#ifndef QT_NO_WHATSTHIS
        cleanKernelsButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        cleanKernelsButton->setText(QApplication::translate("MainWindow", "Clean ancient kernels", 0));
        cleanKernelsButton->setShortcut(QString());
        label_59->setText(QApplication::translate("MainWindow", "Recover space from unused kernels", 0));
        toolBox->setItemText(toolBox->indexOf(page), QApplication::translate("MainWindow", "Advanced user", 0));
#ifndef QT_NO_WHATSTHIS
        cleanButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        cleanButton->setText(QApplication::translate("MainWindow", "Clean system", 0));
        cleanButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        upgradeButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        upgradeButton->setText(QApplication::translate("MainWindow", "Default update system", 0));
        upgradeButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        basicPackagesInstallButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        basicPackagesInstallButton->setText(QApplication::translate("MainWindow", "Exec normal user installation script", 0));
        basicPackagesInstallButton->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        updateReposButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        updateReposButton->setText(QApplication::translate("MainWindow", "Update repos", 0));
        updateReposButton->setShortcut(QString());
        label_14->setText(QApplication::translate("MainWindow", "apt-get -y update", 0));
        label_15->setText(QApplication::translate("MainWindow", "apt-get -y update &&\n"
"apt-get -y upgrade", 0));
        label_16->setText(QApplication::translate("MainWindow", "apt-get -f install &&\n"
"apt-get -y autoremove &&\n"
"apt-get -y autoclean && \n"
"apt-get -y clean", 0));
        label_31->setText(QApplication::translate("MainWindow", "apt-get -y upgrade", 0));
#ifndef QT_NO_WHATSTHIS
        upgradeReposButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        upgradeReposButton->setText(QApplication::translate("MainWindow", "Upgrade repos", 0));
        upgradeReposButton->setShortcut(QString());
        label_25->setText(QApplication::translate("MainWindow", "installs latest version of\n"
"installpackages1 of ubuntupackages on git.\n"
"packages for normal users", 0));
        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("MainWindow", "Normal user", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "System", 0));
        label_5->setText(QApplication::translate("MainWindow", "Coming soon...", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Tweaks", 0));
#ifndef QT_NO_WHATSTHIS
        integrityCheckButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        integrityCheckButton->setText(QString());
        integrityCheckButton->setShortcut(QString());
        label_2->setText(QApplication::translate("MainWindow", "Check system integrity", 0));
        label_3->setText(QApplication::translate("MainWindow", "Fix broken packages (click on each step and check if is solved)", 0));
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_1->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_1->setText(QString());
        fixBrokenPackagesButton_1->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_2->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_2->setText(QString());
        fixBrokenPackagesButton_2->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_3->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_3->setText(QString());
        fixBrokenPackagesButton_3->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_4->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_4->setText(QString());
        fixBrokenPackagesButton_4->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_5->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_5->setText(QString());
        fixBrokenPackagesButton_5->setShortcut(QString());
#ifndef QT_NO_WHATSTHIS
        fixBrokenPackagesButton_6->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        fixBrokenPackagesButton_6->setText(QString());
        fixBrokenPackagesButton_6->setShortcut(QString());
        label_18->setText(QApplication::translate("MainWindow", "shutdown -Fr now", 0));
        label_19->setText(QApplication::translate("MainWindow", "apt-get -y update && apt-get -y upgrade", 0));
        label_20->setText(QApplication::translate("MainWindow", "apt-get -y --fix-broken install", 0));
        label_21->setText(QApplication::translate("MainWindow", "rm /var/lib/apt/lists/* -vf && apt-get -y update", 0));
        label_22->setText(QApplication::translate("MainWindow", "apt-get -f install && apt-get -y autoremove && apt-get -y autoclean &&\n"
"apt-get -y clean", 0));
        label_23->setText(QApplication::translate("MainWindow", "dpkg --configure -a && apt-get -y update", 0));
        label_24->setText(QApplication::translate("MainWindow", "Open Ubuntu Software Center & click repair if proceed", 0));
        label_9->setText(QApplication::translate("MainWindow", "Repair network", 0));
#ifndef QT_NO_WHATSTHIS
        repairNetworkButton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        repairNetworkButton->setText(QString());
        repairNetworkButton->setShortcut(QString());
        label_27->setText(QApplication::translate("MainWindow", "sudo service network-manager restart", 0));
#ifndef QT_NO_WHATSTHIS
        repairGPGKeys->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        repairGPGKeys->setText(QString());
        repairGPGKeys->setShortcut(QString());
        label_28->setText(QApplication::translate("MainWindow", "sudo launchpad-getkeys", 0));
        label_29->setText(QApplication::translate("MainWindow", "Repair missing GPG keys", 0));
        label_30->setText(QApplication::translate("MainWindow", "Be careful, your system will reboot", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Repair", 0));
        unselectAllButton->setText(QApplication::translate("MainWindow", "Unselect All", 0));
        selectAllButton->setText(QApplication::translate("MainWindow", "Select All", 0));
        installSelectedPackagesButton->setText(QApplication::translate("MainWindow", "Install", 0));
        uninstallSelectedPackagesButton_2->setText(QApplication::translate("MainWindow", "Uninstall", 0));
        loadSelectionButton->setText(QApplication::translate("MainWindow", "Load", 0));
        saveSelectionButton->setText(QApplication::translate("MainWindow", "Save", 0));
        checkBox_01->setText(QApplication::translate("MainWindow", "1.freefilesync", 0));
        checkBox_02->setText(QApplication::translate("MainWindow", "2.dropbox", 0));
        checkBox_03->setText(QApplication::translate("MainWindow", "3.megasync", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_23), QApplication::translate("MainWindow", "Backup & Sync", 0));
        checkBox_12->setText(QApplication::translate("MainWindow", "12.keepassx", 0));
        checkBox_13->setText(QApplication::translate("MainWindow", "13.ubuntu-restricted-extras", 0));
        checkBox_14->setText(QApplication::translate("MainWindow", "14.ttf-ancient fonts", 0));
        checkBox_09->setText(QApplication::translate("MainWindow", "9.xorg-edgers", 0));
        checkBox_11->setText(QApplication::translate("MainWindow", "11.graphics-drivers-team", 0));
        checkBox_20->setText(QApplication::translate("MainWindow", "20.gnome-disk-utility", 0));
        checkBox_10->setText(QApplication::translate("MainWindow", "10.oibaf", 0));
        checkBox_21->setText(QApplication::translate("MainWindow", "21.gparted", 0));
        checkBox_08->setText(QApplication::translate("MainWindow", "8.mtp-support", 0));
        checkBox_15->setText(QApplication::translate("MainWindow", "15.synaptic", 0));
        checkBox_05->setText(QApplication::translate("MainWindow", "5.y-ppa-manager", 0));
        checkBox_16->setText(QApplication::translate("MainWindow", "16.preload", 0));
        checkBox_17->setText(QApplication::translate("MainWindow", "17.prelink", 0));
        checkBox_18->setText(QApplication::translate("MainWindow", "18.gdebi", 0));
        checkBox_19->setText(QApplication::translate("MainWindow", "19.ppa-purge", 0));
        checkBox_04->setText(QApplication::translate("MainWindow", "4.apt-fast", 0));
        checkBox_06->setText(QApplication::translate("MainWindow", "6.getdeb", 0));
        checkBox_22->setText(QApplication::translate("MainWindow", "22.gkrellm", 0));
        checkBox_07->setText(QApplication::translate("MainWindow", "7.playdeb", 0));
        checkBox_23->setText(QApplication::translate("MainWindow", "23.mate-tweak", 0));
        checkBox_24->setText(QApplication::translate("MainWindow", "24.recoll", 0));
        checkBox_25->setText(QApplication::translate("MainWindow", "25.brasero", 0));
        checkBox_26->setText(QApplication::translate("MainWindow", "26.k3b", 0));
        checkBox_27->setText(QApplication::translate("MainWindow", "27.gtkorphan", 0));
        checkBox_28->setText(QApplication::translate("MainWindow", "28.byobu", 0));
        checkBox_29->setText(QApplication::translate("MainWindow", "29.gsmartcontrol", 0));
        checkBox_30->setText(QApplication::translate("MainWindow", "30.software-center", 0));
        checkBox_31->setText(QApplication::translate("MainWindow", "31.gnome-software", 0));
        checkBox_32->setText(QApplication::translate("MainWindow", "32.test", 0));
        checkBox_33->setText(QApplication::translate("MainWindow", "33.appgrid", 0));
        checkBox_34->setText(QApplication::translate("MainWindow", "34.mintStick", 0));
        checkBox_35->setText(QApplication::translate("MainWindow", "35.mate-dock-applet", 0));
        checkBox_36->setText(QApplication::translate("MainWindow", "36.extundelete", 0));
        checkBox_37->setText(QApplication::translate("MainWindow", "37.cairo-dock", 0));
        checkBox_38->setText(QApplication::translate("MainWindow", "38.ubuntu-after-install", 0));
        checkBox_39->setText(QApplication::translate("MainWindow", "39.ubutricks", 0));
        checkBox_40->setText(QApplication::translate("MainWindow", "40.postinstallerf", 0));
        checkBox_46->setText(QApplication::translate("MainWindow", "46.clipit", 0));
        checkBox_45->setText(QApplication::translate("MainWindow", "45.bleachbit", 0));
        checkBox_44->setText(QApplication::translate("MainWindow", "44.grub-customizer", 0));
        checkBox_43->setText(QApplication::translate("MainWindow", "43.synapse", 0));
        checkBox_42->setText(QApplication::translate("MainWindow", "42.converseen", 0));
        checkBox_41->setText(QApplication::translate("MainWindow", "41.teamviewer", 0));
        checkBox_47->setText(QApplication::translate("MainWindow", "47.screenfetch", 0));
        checkBox_48->setText(QApplication::translate("MainWindow", "48.i-nex", 0));
        checkBox_49->setText(QApplication::translate("MainWindow", "49.ANGRYsearch", 0));
        checkBox_50->setText(QApplication::translate("MainWindow", "50.fish-shell", 0));
        checkBox_51->setText(QApplication::translate("MainWindow", "51.furiusisomount", 0));
        checkBox_52->setText(QApplication::translate("MainWindow", "52.ddrescue-gui", 0));
        checkBox_53->setText(QApplication::translate("MainWindow", "53.unetbootin", 0));
        checkBox_54->setText(QApplication::translate("MainWindow", "54.manpages-es", 0));
        checkBox_55->setText(QApplication::translate("MainWindow", "55.asterisk-on-cli-passwords", 0));
        checkBox_56->setText(QApplication::translate("MainWindow", "56.disable-system-crash-reports", 0));
        checkBox_130->setText(QApplication::translate("MainWindow", "130.spaceview", 0));
        checkBox_132->setText(QApplication::translate("MainWindow", "132.ukku", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_11), QApplication::translate("MainWindow", "OS & Utilities", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_12), QApplication::translate("MainWindow", "Desktop Environment", 0));
        checkBox_57->setText(QApplication::translate("MainWindow", "57.vibrancy-colors", 0));
        checkBox_58->setText(QApplication::translate("MainWindow", "58.flatabulous-theme", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QApplication::translate("MainWindow", "Themes", 0));
        checkBox_59->setText(QApplication::translate("MainWindow", "59.aspell", 0));
        checkBox_60->setText(QApplication::translate("MainWindow", "60.myspell", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_13), QApplication::translate("MainWindow", "Lang. packages", 0));
        checkBox_61->setText(QApplication::translate("MainWindow", "61.gufw", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QApplication::translate("MainWindow", "Security & Privacy", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_7), QApplication::translate("MainWindow", "CD/DVD Tools", 0));
        checkBox_62->setText(QApplication::translate("MainWindow", "62.gimp", 0));
        checkBox_63->setText(QApplication::translate("MainWindow", "63.gimp-edge", 0));
        checkBox_64->setText(QApplication::translate("MainWindow", "64.krita-testing", 0));
        checkBox_65->setText(QApplication::translate("MainWindow", "65.gnome-exe-thumbnailer", 0));
        checkBox_66->setText(QApplication::translate("MainWindow", "66.shutter", 0));
        checkBox_67->setText(QApplication::translate("MainWindow", "67.inkscape-stable", 0));
        checkBox_68->setText(QApplication::translate("MainWindow", "68.inkscape-trunk", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_8), QApplication::translate("MainWindow", "Photos & Graphics", 0));
        checkBox_69->setText(QApplication::translate("MainWindow", "69.qmmp", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_9), QApplication::translate("MainWindow", "Audio & Music", 0));
        checkBox_70->setText(QApplication::translate("MainWindow", "70.kazam", 0));
        checkBox_71->setText(QApplication::translate("MainWindow", "71.sopcast", 0));
        checkBox_72->setText(QApplication::translate("MainWindow", "72.smplayer", 0));
        checkBox_73->setText(QApplication::translate("MainWindow", "73.handbrake", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_10), QApplication::translate("MainWindow", "Videos & Movies", 0));
        checkBox_74->setText(QApplication::translate("MainWindow", "74.ffmpeg", 0));
        checkBox_75->setText(QApplication::translate("MainWindow", "75.vlc-stable", 0));
        checkBox_76->setText(QApplication::translate("MainWindow", "76.vlc-daily", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_14), QApplication::translate("MainWindow", "All multimedia content", 0));
        checkBox_77->setText(QApplication::translate("MainWindow", "77.notepadqq", 0));
        checkBox_78->setText(QApplication::translate("MainWindow", "78.openjdk-8", 0));
        checkBox_79->setText(QApplication::translate("MainWindow", "79.openjdk-7", 0));
        checkBox_80->setText(QApplication::translate("MainWindow", "80.meld", 0));
        checkBox_81->setText(QApplication::translate("MainWindow", "81.dev-utils", 0));
        checkBox_82->setText(QApplication::translate("MainWindow", "82.git-stable", 0));
        checkBox_83->setText(QApplication::translate("MainWindow", "83.smartgit", 0));
        checkBox_84->setText(QApplication::translate("MainWindow", "84.flatpak", 0));
        checkBox_85->setText(QApplication::translate("MainWindow", "85.dia", 0));
        checkBox_86->setText(QApplication::translate("MainWindow", "86.blender", 0));
        checkBox_87->setText(QApplication::translate("MainWindow", "87.fritzing", 0));
        checkBox_88->setText(QApplication::translate("MainWindow", "88.uecide", 0));
        checkBox_89->setText(QApplication::translate("MainWindow", "89.arduino-ide", 0));
        checkBox_90->setText(QApplication::translate("MainWindow", "90.arduino-studio", 0));
        checkBox_91->setText(QApplication::translate("MainWindow", "91.git-rc", 0));
        checkBox_92->setText(QApplication::translate("MainWindow", "92.git-gui", 0));
        checkBox_93->setText(QApplication::translate("MainWindow", "93.Qt-Linux", 0));
        checkBox_94->setText(QApplication::translate("MainWindow", "94.kicad", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_15), QApplication::translate("MainWindow", "Development", 0));
        checkBox_100->setText(QApplication::translate("MainWindow", "100.vivaldi-browser", 0));
        checkBox_101->setText(QApplication::translate("MainWindow", "101.google-chrome-stable", 0));
        checkBox_102->setText(QApplication::translate("MainWindow", "102.google-chrome-unstable", 0));
        checkBox_104->setText(QApplication::translate("MainWindow", "104.firefox", 0));
        checkBox_105->setText(QApplication::translate("MainWindow", "105.firefox-trunk", 0));
        checkBox_103->setText(QApplication::translate("MainWindow", "103.chromium", 0));
        checkBox_106->setText(QApplication::translate("MainWindow", "106.ubuntu-mozilla-security", 0));
        checkBox_107->setText(QApplication::translate("MainWindow", "107.pepper-flash-for-chromium", 0));
        checkBox_108->setText(QApplication::translate("MainWindow", "108.pepper-flash-for-firefox", 0));
        checkBox_109->setText(QApplication::translate("MainWindow", "109.tor-browser", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_16), QApplication::translate("MainWindow", "Web Browsers", 0));
        checkBox_110->setText(QApplication::translate("MainWindow", "110.skype", 0));
        checkBox_111->setText(QApplication::translate("MainWindow", "111.mumble", 0));
        checkBox_112->setText(QApplication::translate("MainWindow", "112.wire", 0));
        checkBox_113->setText(QApplication::translate("MainWindow", "113.telegram", 0));
        checkBox_114->setText(QApplication::translate("MainWindow", "114.Facebook-Messenger-Desktop", 0));
        checkBox_115->setText(QApplication::translate("MainWindow", "115.Whatsie", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_17), QApplication::translate("MainWindow", "Social", 0));
        checkBox_116->setText(QApplication::translate("MainWindow", "116.compress-uncompress-utils", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_18), QApplication::translate("MainWindow", "File Management", 0));
        checkBox_117->setText(QApplication::translate("MainWindow", "117.jdownloader-beta", 0));
        checkBox_118->setText(QApplication::translate("MainWindow", "118.jdownloader-stable", 0));
        checkBox_119->setText(QApplication::translate("MainWindow", "119.peerflix", 0));
        checkBox_120->setText(QApplication::translate("MainWindow", "120.samba", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_19), QApplication::translate("MainWindow", "File Sharing", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_20), QApplication::translate("MainWindow", "News & Books", 0));
        checkBox_121->setText(QApplication::translate("MainWindow", "121.evolution", 0));
        checkBox_122->setText(QApplication::translate("MainWindow", "122.libreoffice", 0));
        checkBox_123->setText(QApplication::translate("MainWindow", "123.qpdfview", 0));
        checkBox_124->setText(QApplication::translate("MainWindow", "124.thunderbird-nightly", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_21), QApplication::translate("MainWindow", "Office & Productivity", 0));
        checkBox_125->setText(QApplication::translate("MainWindow", "125.steam", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_22), QApplication::translate("MainWindow", "Games", 0));
        checkBox_126->setText(QApplication::translate("MainWindow", "126.uninstallpackages", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_24), QApplication::translate("MainWindow", "Extra", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Install packages", 0));
        menuNuevo->setTitle(QApplication::translate("MainWindow", "File", 0));
        menuEdici_n->setTitle(QApplication::translate("MainWindow", "Edit", 0));
        menuAyuda->setTitle(QApplication::translate("MainWindow", "Help", 0));
        editToolBar->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
