#!/bin/bash

#### oracle-java 6 7 8
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-fast -y update

#### oracle-java 6
#sudo apt-fast -y install oracle-java6-installer
#sudo apt-fast install oracle-java6-set-default

#### oracle-java 7
#sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#sudo apt-fast -y install oracle-java7-installer
#sudo update-java-alternatives -s java-7-oracle
#sudo apt-fast install oracle-java7-set-default

#### oracle-java 8
sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-fast -y install oracle-java8-installer
sudo update-java-alternatives -s java-8-oracle
sudo apt-fast install oracle-java8-set-default

#### oracle-java 9
#sudo add-apt-repository -y ppa:webupd8team/java
#sudo apt-get -y update
#sudo apt-get -y install oracle-java9-installer
#sudo apt-get -y install oracle-java9-set-default